<?xml version="1.0"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
	<id>https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom</id>
	<title>Wikipedia &quot;On this day...&quot; feed</title>
	<link rel="self" type="application/atom+xml" href="https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom"/>
	<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Main_Page"/>
	<updated>2021-12-21T18:27:37Z</updated>
	<subtitle>Historical events on this day</subtitle>
	<generator>MediaWiki 1.38.0-wmf.13</generator>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211212000000/en</id>
		<title>On this day: December 12</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211212000000/en"/>
		<updated>2021-12-12T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/b&gt;: Beginning of the &lt;b&gt;&lt;a href=&quot;/wiki/Icelandic_Christmas_folklore#Yule_lads&quot; title=&quot;Icelandic Christmas folklore&quot;&gt;Yule Lads&lt;/a&gt;&lt;/b&gt;&lt;span class=&quot;nowrap&quot;&gt;&amp;#39;&lt;/span&gt; arrival in Iceland
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 150px;&quot;&gt;
&lt;a href=&quot;/wiki/File:OaksCollieryDisaster1866.jpg&quot; class=&quot;image&quot; title=&quot;Oaks Colliery explosion&quot;&gt;&lt;img alt=&quot;Oaks Colliery explosion&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/OaksCollieryDisaster1866.jpg/150px-OaksCollieryDisaster1866.jpg&quot; decoding=&quot;async&quot; width=&quot;150&quot; height=&quot;131&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/OaksCollieryDisaster1866.jpg/225px-OaksCollieryDisaster1866.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d9/OaksCollieryDisaster1866.jpg/300px-OaksCollieryDisaster1866.jpg 2x&quot; data-file-width=&quot;464&quot; data-file-height=&quot;405&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Oaks Colliery explosion&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1388&quot; title=&quot;1388&quot;&gt;1388&lt;/a&gt; – Unable to defend her possessions, &lt;a href=&quot;/wiki/Maria_of_Enghien&quot; title=&quot;Maria of Enghien&quot;&gt;Maria of Enghien&lt;/a&gt; sold the &lt;b&gt;&lt;a href=&quot;/wiki/Lordship_of_Argos_and_Nauplia&quot; title=&quot;Lordship of Argos and Nauplia&quot;&gt;lordship of Argos and Nauplia&lt;/a&gt;&lt;/b&gt; to the &lt;a href=&quot;/wiki/Republic_of_Venice&quot; title=&quot;Republic of Venice&quot;&gt;Republic of Venice&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1866&quot; title=&quot;1866&quot;&gt;1866&lt;/a&gt; – England's worst mining disaster occurred when &lt;b&gt;&lt;a href=&quot;/wiki/Oaks_explosion&quot; title=&quot;Oaks explosion&quot;&gt;a series of explosions&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(depicted)&lt;/i&gt; caused by &lt;a href=&quot;/wiki/Firedamp&quot; title=&quot;Firedamp&quot;&gt;flammable gases&lt;/a&gt; ripped through the Oaks Colliery, killing 361 people.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1905&quot; title=&quot;1905&quot;&gt;1905&lt;/a&gt; – In support of the &lt;a href=&quot;/wiki/Moscow_uprising_of_1905&quot; title=&quot;Moscow uprising of 1905&quot;&gt;December Uprising&lt;/a&gt; in Moscow, the Council of Workers' Deputies of Kiev staged a mass uprising, establishing the &lt;b&gt;&lt;a href=&quot;/wiki/Shuliavka_Republic&quot; title=&quot;Shuliavka Republic&quot;&gt;Shuliavka Republic&lt;/a&gt;&lt;/b&gt; in the city.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – &lt;a href=&quot;/wiki/The_Holocaust&quot; title=&quot;The Holocaust&quot;&gt;The Holocaust&lt;/a&gt;: At &lt;b&gt;&lt;a href=&quot;/wiki/Reich_Chancellery_meeting_of_12_December_1941&quot; title=&quot;Reich Chancellery meeting of 12 December 1941&quot;&gt;a Nazi Party meeting&lt;/a&gt;&lt;/b&gt; in the &lt;a href=&quot;/wiki/Reich_Chancellery&quot; title=&quot;Reich Chancellery&quot;&gt;Reich Chancellery&lt;/a&gt;, &lt;a href=&quot;/wiki/Adolf_Hitler&quot; title=&quot;Adolf Hitler&quot;&gt;Adolf Hitler&lt;/a&gt; declared the imminent destruction of the &lt;a href=&quot;/wiki/Jews&quot; title=&quot;Jews&quot;&gt;Jewish&lt;/a&gt; people.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1985&quot; title=&quot;1985&quot;&gt;1985&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Arrow_Air_Flight_1285&quot; title=&quot;Arrow Air Flight 1285&quot;&gt;Arrow Air Flight&amp;#160;1285&lt;/a&gt;&lt;/b&gt; crashed after takeoff in &lt;a href=&quot;/wiki/Gander_International_Airport&quot; title=&quot;Gander International Airport&quot;&gt;Gander&lt;/a&gt;, &lt;a href=&quot;/wiki/Newfoundland_and_Labrador&quot; title=&quot;Newfoundland and Labrador&quot;&gt;Newfoundland&lt;/a&gt;, Canada, killing 256 people, including 248 members of the &lt;a href=&quot;/wiki/United_States_Army&quot; title=&quot;United States Army&quot;&gt;U.S. Army&lt;/a&gt;'s &lt;a href=&quot;/wiki/101st_Airborne_Division&quot; title=&quot;101st Airborne Division&quot;&gt;101st Airborne Division&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Johann_Christoph_Gottsched&quot; title=&quot;Johann Christoph Gottsched&quot;&gt;Johann Christoph Gottsched&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1766)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Gustave_Flaubert&quot; title=&quot;Gustave Flaubert&quot;&gt;Gustave Flaubert&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1821)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Henrietta_Swan_Leavitt&quot; title=&quot;Henrietta Swan Leavitt&quot;&gt;Henrietta Swan Leavitt&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1921)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_11&quot; title=&quot;December 11&quot;&gt;December 11&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211213000000/en</id>
		<title>On this day: December 13</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211213000000/en"/>
		<updated>2021-12-13T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/b&gt;:
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 117px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Wojciech_Jaruzelski.jpg&quot; class=&quot;image&quot; title=&quot;Wojciech Jaruzelski&quot;&gt;&lt;img alt=&quot;Wojciech Jaruzelski&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/70/Wojciech_Jaruzelski.jpg/117px-Wojciech_Jaruzelski.jpg&quot; decoding=&quot;async&quot; width=&quot;117&quot; height=&quot;167&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/70/Wojciech_Jaruzelski.jpg/176px-Wojciech_Jaruzelski.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/70/Wojciech_Jaruzelski.jpg/234px-Wojciech_Jaruzelski.jpg 2x&quot; data-file-width=&quot;421&quot; data-file-height=&quot;600&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Wojciech Jaruzelski&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1643&quot; title=&quot;1643&quot;&gt;1643&lt;/a&gt; – &lt;a href=&quot;/wiki/First_English_Civil_War&quot; title=&quot;First English Civil War&quot;&gt;First English Civil War&lt;/a&gt;: &lt;a href=&quot;/wiki/Roundhead&quot; title=&quot;Roundhead&quot;&gt;Roundhead&lt;/a&gt; forces under &lt;a href=&quot;/wiki/William_Waller&quot; title=&quot;William Waller&quot;&gt;Sir William Waller&lt;/a&gt; led &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Alton&quot; title=&quot;Battle of Alton&quot;&gt;a successful surprise attack&lt;/a&gt;&lt;/b&gt; on a winter garrison of &lt;a href=&quot;/wiki/Cavalier&quot; title=&quot;Cavalier&quot;&gt;Royalist&lt;/a&gt; infantry and cavalry.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1769&quot; title=&quot;1769&quot;&gt;1769&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Dartmouth_College&quot; title=&quot;Dartmouth College&quot;&gt;Dartmouth College&lt;/a&gt;&lt;/b&gt;, in present-day &lt;a href=&quot;/wiki/Hanover,_New_Hampshire&quot; title=&quot;Hanover, New Hampshire&quot;&gt;Hanover, New Hampshire&lt;/a&gt;, was established by &lt;a href=&quot;/wiki/Royal_charter&quot; title=&quot;Royal charter&quot;&gt;royal charter&lt;/a&gt;, becoming the last university to be founded in the &lt;a href=&quot;/wiki/Thirteen_Colonies&quot; title=&quot;Thirteen Colonies&quot;&gt;Thirteen Colonies&lt;/a&gt; before the &lt;a href=&quot;/wiki/American_Revolution&quot; title=&quot;American Revolution&quot;&gt;American Revolution&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1981&quot; title=&quot;1981&quot;&gt;1981&lt;/a&gt; – Polish prime minister &lt;a href=&quot;/wiki/Wojciech_Jaruzelski&quot; title=&quot;Wojciech Jaruzelski&quot;&gt;Wojciech Jaruzelski&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt; performed a &lt;a href=&quot;/wiki/Self-coup&quot; title=&quot;Self-coup&quot;&gt;self-coup&lt;/a&gt; by &lt;b&gt;&lt;a href=&quot;/wiki/Martial_law_in_Poland&quot; title=&quot;Martial law in Poland&quot;&gt;declaring martial law&lt;/a&gt;&lt;/b&gt;, suspending the trade union &lt;a href=&quot;/wiki/Solidarity_(Polish_trade_union)&quot; title=&quot;Solidarity (Polish trade union)&quot;&gt;Solidarity&lt;/a&gt; and imprisoning many of its leaders.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2001&quot; title=&quot;2001&quot;&gt;2001&lt;/a&gt; – The &lt;a href=&quot;/wiki/Parliament_of_India&quot; title=&quot;Parliament of India&quot;&gt;Parliament of India&lt;/a&gt; was &lt;b&gt;&lt;a href=&quot;/wiki/2001_Indian_Parliament_attack&quot; title=&quot;2001 Indian Parliament attack&quot;&gt;attacked by five gunmen&lt;/a&gt;&lt;/b&gt;, who killed nine people.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2011&quot; title=&quot;2011&quot;&gt;2011&lt;/a&gt; – After murdering a woman at his home, a man &lt;b&gt;&lt;a href=&quot;/wiki/2011_Li%C3%A8ge_attack&quot; title=&quot;2011 Liège attack&quot;&gt;threw grenades and fired a rifle&lt;/a&gt;&lt;/b&gt; at crowds in &lt;a href=&quot;/wiki/Li%C3%A8ge&quot; title=&quot;Liège&quot;&gt;Liège&lt;/a&gt;, Belgium, killing 6 people and injuring 125 others, before killing himself.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Pope_Callixtus_II&quot; title=&quot;Pope Callixtus II&quot;&gt;Pope Callixtus&amp;#160;II&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1124)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Emily_Carr&quot; title=&quot;Emily Carr&quot;&gt;Emily Carr&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1871)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Hans-Joachim_Marseille&quot; title=&quot;Hans-Joachim Marseille&quot;&gt;Hans-Joachim Marseille&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1919)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211214000000/en</id>
		<title>On this day: December 14</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211214000000/en"/>
		<updated>2021-12-14T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Martyred_Intellectuals_Day&quot; title=&quot;Martyred Intellectuals Day&quot;&gt;Martyred Intellectuals Day&lt;/a&gt;&lt;/b&gt; in Bangladesh (&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt;); &lt;b&gt;&lt;a href=&quot;/wiki/Monkey_Day&quot; title=&quot;Monkey Day&quot;&gt;Monkey Day&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 125px;&quot;&gt;
&lt;a href=&quot;/wiki/File:TangWenzongAlt.jpg&quot; class=&quot;image&quot; title=&quot;Emperor Wenzong of Tang&quot;&gt;&lt;img alt=&quot;Emperor Wenzong of Tang&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/TangWenzongAlt.jpg/125px-TangWenzongAlt.jpg&quot; decoding=&quot;async&quot; width=&quot;125&quot; height=&quot;156&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/TangWenzongAlt.jpg/188px-TangWenzongAlt.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9a/TangWenzongAlt.jpg/250px-TangWenzongAlt.jpg 2x&quot; data-file-width=&quot;276&quot; data-file-height=&quot;345&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Emperor Wenzong of Tang&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/835&quot; title=&quot;835&quot;&gt;835&lt;/a&gt; – In the &lt;b&gt;&lt;a href=&quot;/wiki/Sweet_Dew_incident&quot; title=&quot;Sweet Dew incident&quot;&gt;Sweet Dew incident&lt;/a&gt;&lt;/b&gt;, &lt;a href=&quot;/wiki/Emperor_Wenzong_of_Tang&quot; title=&quot;Emperor Wenzong of Tang&quot;&gt;Emperor Wenzong&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt; of the &lt;a href=&quot;/wiki/Tang_dynasty&quot; title=&quot;Tang dynasty&quot;&gt;Tang dynasty&lt;/a&gt; conspired to kill the powerful &lt;a href=&quot;/wiki/Eunuch&quot; title=&quot;Eunuch&quot;&gt;eunuchs&lt;/a&gt; of the Tang court, but the plot was foiled.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1863&quot; title=&quot;1863&quot;&gt;1863&lt;/a&gt; – &lt;a href=&quot;/wiki/American_Civil_War&quot; title=&quot;American Civil War&quot;&gt;American Civil War&lt;/a&gt;: The &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Bean%27s_Station&quot; title=&quot;Battle of Bean&amp;#39;s Station&quot;&gt;Battle of Bean's Station&lt;/a&gt;&lt;/b&gt;, the final battle of the &lt;a href=&quot;/wiki/Knoxville_campaign&quot; title=&quot;Knoxville campaign&quot;&gt;Knoxville campaign&lt;/a&gt;, was fought in &lt;a href=&quot;/wiki/Grainger_County,_Tennessee&quot; title=&quot;Grainger County, Tennessee&quot;&gt;Grainger County, Tennessee&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1918&quot; title=&quot;1918&quot;&gt;1918&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/1918_United_Kingdom_general_election&quot; title=&quot;1918 United Kingdom general election&quot;&gt;first British general election with female voters&lt;/a&gt;&lt;/b&gt; took place, with women over the age of thirty permitted to vote.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1981&quot; title=&quot;1981&quot;&gt;1981&lt;/a&gt; – The &lt;a href=&quot;/wiki/Knesset&quot; title=&quot;Knesset&quot;&gt;Knesset&lt;/a&gt; passed the &lt;a href=&quot;/wiki/Golan_Heights_Law&quot; title=&quot;Golan Heights Law&quot;&gt;Golan Heights Law&lt;/a&gt;, extending Israeli &quot;laws, jurisdiction and administration&quot; to the &lt;b&gt;&lt;a href=&quot;/wiki/Golan_Heights&quot; title=&quot;Golan Heights&quot;&gt;Golan Heights&lt;/a&gt;&lt;/b&gt;, effectively &lt;a href=&quot;/wiki/Annexation&quot; title=&quot;Annexation&quot;&gt;annexing&lt;/a&gt; the territory internationally recognized as part of Syria.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1998&quot; title=&quot;1998&quot;&gt;1998&lt;/a&gt; – &lt;a href=&quot;/wiki/Kosovo_War&quot; title=&quot;Kosovo War&quot;&gt;Kosovo War&lt;/a&gt;: &lt;a href=&quot;/wiki/Serbia_and_Montenegro&quot; title=&quot;Serbia and Montenegro&quot;&gt;Yugoslav&lt;/a&gt; forces &lt;b&gt;&lt;a href=&quot;/wiki/December_14,_1998,_Albanian%E2%80%93Yugoslav_border_ambush&quot; title=&quot;December 14, 1998, Albanian–Yugoslav border ambush&quot;&gt;ambushed a group&lt;/a&gt;&lt;/b&gt; of &lt;a href=&quot;/wiki/Kosovo_Liberation_Army&quot; title=&quot;Kosovo Liberation Army&quot;&gt;Kosovo Liberation Army&lt;/a&gt; militants attempting to smuggle weapons into Yugoslavia from Albania.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Niccol%C3%B2_Perotti&quot; title=&quot;Niccolò Perotti&quot;&gt;Niccolò Perotti&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1480)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/DeFord_Bailey&quot; title=&quot;DeFord Bailey&quot;&gt;DeFord Bailey&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1899)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Kim_Beazley&quot; title=&quot;Kim Beazley&quot;&gt;Kim Beazley&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1948)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211215000000/en</id>
		<title>On this day: December 15</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211215000000/en"/>
		<updated>2021-12-15T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 121px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Adolf_Eichmann_at_Trial1961.jpg&quot; class=&quot;image&quot; title=&quot;Adolf Eichmann on trial&quot;&gt;&lt;img alt=&quot;Adolf Eichmann on trial&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Adolf_Eichmann_at_Trial1961.jpg/121px-Adolf_Eichmann_at_Trial1961.jpg&quot; decoding=&quot;async&quot; width=&quot;121&quot; height=&quot;161&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Adolf_Eichmann_at_Trial1961.jpg/182px-Adolf_Eichmann_at_Trial1961.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Adolf_Eichmann_at_Trial1961.jpg/242px-Adolf_Eichmann_at_Trial1961.jpg 2x&quot; data-file-width=&quot;1753&quot; data-file-height=&quot;2337&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Adolf Eichmann on trial&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/687&quot; title=&quot;687&quot;&gt;687&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Pope_Sergius_I&quot; title=&quot;Pope Sergius I&quot;&gt;Sergius&lt;/a&gt;&lt;/b&gt; was elected pope, ending the last disputed period of &lt;i&gt;&lt;a href=&quot;/wiki/Sede_vacante&quot; title=&quot;Sede vacante&quot;&gt;sede vacante&lt;/a&gt;&lt;/i&gt; during the &lt;a href=&quot;/wiki/Byzantine_Papacy&quot; title=&quot;Byzantine Papacy&quot;&gt;Byzantine Papacy&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1025&quot; title=&quot;1025&quot;&gt;1025&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Constantine_VIII&quot; title=&quot;Constantine VIII&quot;&gt;Constantine&amp;#160;VIII&lt;/a&gt;&lt;/b&gt; became the sole &lt;a href=&quot;/wiki/Byzantine_Empire&quot; title=&quot;Byzantine Empire&quot;&gt;Byzantine&lt;/a&gt; emperor, 63 years after being crowned co-emperor.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1946&quot; title=&quot;1946&quot;&gt;1946&lt;/a&gt; – U.S.-backed Iranian troops brought an end to the &lt;b&gt;&lt;a href=&quot;/wiki/Iran_crisis_of_1946&quot; title=&quot;Iran crisis of 1946&quot;&gt;Iran crisis&lt;/a&gt;&lt;/b&gt; when they marched on the breakaway &lt;a href=&quot;/wiki/Republic_of_Mahabad&quot; title=&quot;Republic of Mahabad&quot;&gt;Republic of Mahabad&lt;/a&gt; and recaptured the territory.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1961&quot; title=&quot;1961&quot;&gt;1961&lt;/a&gt; – Former Nazi leader &lt;b&gt;&lt;a href=&quot;/wiki/Adolf_Eichmann&quot; title=&quot;Adolf Eichmann&quot;&gt;Adolf Eichmann&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; was sentenced to death after being found guilty on fifteen criminal charges, including &lt;a href=&quot;/wiki/War_crime&quot; title=&quot;War crime&quot;&gt;war crimes&lt;/a&gt; and &lt;a href=&quot;/wiki/Crimes_against_humanity&quot; title=&quot;Crimes against humanity&quot;&gt;crimes against humanity&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1981&quot; title=&quot;1981&quot;&gt;1981&lt;/a&gt; – The Iraqi &lt;a href=&quot;/wiki/Shia_Islam&quot; title=&quot;Shia Islam&quot;&gt;Shia&lt;/a&gt; Islamist group &lt;a href=&quot;/wiki/Islamic_Dawa_Party&quot; title=&quot;Islamic Dawa Party&quot;&gt;al-Dawa&lt;/a&gt; carried out &lt;b&gt;&lt;a href=&quot;/wiki/Iraqi_embassy_bombing_in_Beirut&quot; title=&quot;Iraqi embassy bombing in Beirut&quot;&gt;one of the first modern suicide bombings&lt;/a&gt;&lt;/b&gt;, targeting the Iraqi embassy in Beirut, Lebanon, resulting in 61 deaths and 110 injuries.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/David_Teniers_the_Younger&quot; title=&quot;David Teniers the Younger&quot;&gt;David Teniers the Younger&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;baptised&quot;&gt;bapt.&lt;/abbr&gt;&amp;#160;1610)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Florence_Jepperson_Madsen&quot; title=&quot;Florence Jepperson Madsen&quot;&gt;Florence Jepperson Madsen&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1886)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Vallabhbhai_Patel&quot; title=&quot;Vallabhbhai Patel&quot;&gt;Vallabhbhai Patel&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1950)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211216000000/en</id>
		<title>On this day: December 16</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211216000000/en"/>
		<updated>2021-12-16T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Day_of_Reconciliation&quot; title=&quot;Day of Reconciliation&quot;&gt;Day of Reconciliation&lt;/a&gt;&lt;/b&gt; in South Africa
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: px;&quot;&gt;
&lt;div class=&quot;mediaContainer&quot; style=&quot;width:220px&quot;&gt;&lt;audio id=&quot;mwe_player_0&quot; controls=&quot;&quot; preload=&quot;none&quot; style=&quot;width:220px&quot; class=&quot;kskin&quot; data-durationhint=&quot;604.536&quot; data-startoffset=&quot;0&quot; data-mwtitle=&quot;Antonin_Dvorak_-_symphony_no._9_in_e_minor_&amp;#39;from_the_new_world&amp;#39;,_op._95_-_i._adagio_-_allegro_molto.ogg&quot; data-mwprovider=&quot;wikimediacommons&quot;&gt;&lt;source src=&quot;//upload.wikimedia.org/wikipedia/commons/5/5c/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_i._adagio_-_allegro_molto.ogg&quot; type=&quot;audio/ogg; codecs=&amp;quot;vorbis&amp;quot;&quot; data-title=&quot;Original Ogg file (176 kbps)&quot; data-shorttitle=&quot;Ogg source&quot; data-width=&quot;0&quot; data-height=&quot;0&quot; data-bandwidth=&quot;175824&quot; /&gt;&lt;source src=&quot;//upload.wikimedia.org/wikipedia/commons/transcoded/5/5c/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_i._adagio_-_allegro_molto.ogg/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_i._adagio_-_allegro_molto.ogg.mp3&quot; type=&quot;audio/mpeg&quot; data-title=&quot;MP3&quot; data-shorttitle=&quot;MP3&quot; data-transcodekey=&quot;mp3&quot; data-width=&quot;0&quot; data-height=&quot;0&quot; data-bandwidth=&quot;215408&quot; /&gt;&lt;/audio&gt;&lt;/div&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;First movement of Dvořák's &lt;br /&gt;&lt;i&gt;New World Symphony&lt;/i&gt;&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1707&quot; title=&quot;1707&quot;&gt;1707&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/H%C5%8Dei_eruption&quot; title=&quot;Hōei eruption&quot;&gt;The last recorded eruption&lt;/a&gt;&lt;/b&gt; of Japan's &lt;a href=&quot;/wiki/Mount_Fuji&quot; title=&quot;Mount Fuji&quot;&gt;Mount Fuji&lt;/a&gt; released some 800&amp;#160;million&amp;#160;m&lt;sup&gt;3&lt;/sup&gt; (28&amp;#160;billion&amp;#160;cu&amp;#160;ft) of &lt;a href=&quot;/wiki/Volcanic_ash&quot; title=&quot;Volcanic ash&quot;&gt;volcanic ash&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1893&quot; title=&quot;1893&quot;&gt;1893&lt;/a&gt; – Czech composer &lt;a href=&quot;/wiki/Anton%C3%ADn_Dvo%C5%99%C3%A1k&quot; title=&quot;Antonín Dvořák&quot;&gt;Antonín Dvořák&lt;/a&gt;'s &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Symphony_No._9_(Dvo%C5%99%C3%A1k)&quot; title=&quot;Symphony No. 9 (Dvořák)&quot;&gt;New World Symphony&lt;/a&gt;&lt;/b&gt;&lt;/i&gt; &lt;i&gt;(audio featured)&lt;/i&gt; premiered at &lt;a href=&quot;/wiki/Carnegie_Hall&quot; title=&quot;Carnegie Hall&quot;&gt;Carnegie Hall&lt;/a&gt; in New York City.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1918&quot; title=&quot;1918&quot;&gt;1918&lt;/a&gt; – &lt;a href=&quot;/wiki/Vincas_Mickevi%C4%8Dius-Kapsukas&quot; title=&quot;Vincas Mickevičius-Kapsukas&quot;&gt;Vincas Mickevičius-Kapsukas&lt;/a&gt; declared the formation of the &lt;b&gt;&lt;a href=&quot;/wiki/Lithuanian_Soviet_Socialist_Republic_(1918%E2%80%9319)&quot; class=&quot;mw-redirect&quot; title=&quot;Lithuanian Soviet Socialist Republic (1918–19)&quot;&gt;Lithuanian Soviet Socialist Republic&lt;/a&gt;&lt;/b&gt;, a puppet state created by Soviet Russia to justify the &lt;a href=&quot;/wiki/Lithuanian%E2%80%93Soviet_War&quot; title=&quot;Lithuanian–Soviet War&quot;&gt;Lithuanian–Soviet War&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt; – The surrender of &lt;a href=&quot;/wiki/East_Pakistan&quot; title=&quot;East Pakistan&quot;&gt;East Pakistani&lt;/a&gt; forces in &lt;a href=&quot;/wiki/Dhaka&quot; title=&quot;Dhaka&quot;&gt;Dacca&lt;/a&gt; concluded the &lt;b&gt;&lt;a href=&quot;/wiki/Bangladesh_Liberation_War&quot; title=&quot;Bangladesh Liberation War&quot;&gt;Bangladesh Liberation War&lt;/a&gt;&lt;/b&gt; and the &lt;b&gt;&lt;a href=&quot;/wiki/Indo-Pakistani_War_of_1971&quot; title=&quot;Indo-Pakistani War of 1971&quot;&gt;Indo-Pakistani War&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2014&quot; title=&quot;2014&quot;&gt;2014&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Lindt_Cafe_siege&quot; title=&quot;Lindt Cafe siege&quot;&gt;A hostage crisis&lt;/a&gt;&lt;/b&gt; in a &lt;a href=&quot;/wiki/Lindt#Lindt_chocolate_cafés&quot; title=&quot;Lindt&quot;&gt;Lindt chocolate café&lt;/a&gt; in Sydney, Australia, ended with police storming the building, killing the perpetrator and one of the hostages.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Haakon_IV_of_Norway&quot; title=&quot;Haakon IV of Norway&quot;&gt;Haakon&amp;#160;IV of Norway&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1263)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Maria_Rundell&quot; title=&quot;Maria Rundell&quot;&gt;Maria Rundell&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1828)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Carol_Browner&quot; title=&quot;Carol Browner&quot;&gt;Carol Browner&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1955)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_17&quot; title=&quot;December 17&quot;&gt;December 17&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211217000000/en</id>
		<title>On this day: December 17</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211217000000/en"/>
		<updated>2021-12-17T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_17&quot; title=&quot;December 17&quot;&gt;December 17&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 176px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Darwin_Rebellion_4.jpg&quot; class=&quot;image&quot; title=&quot;Demonstrators in the Darwin rebellion&quot;&gt;&lt;img alt=&quot;Demonstrators in the Darwin rebellion&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Darwin_Rebellion_4.jpg/176px-Darwin_Rebellion_4.jpg&quot; decoding=&quot;async&quot; width=&quot;176&quot; height=&quot;111&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Darwin_Rebellion_4.jpg/264px-Darwin_Rebellion_4.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Darwin_Rebellion_4.jpg/352px-Darwin_Rebellion_4.jpg 2x&quot; data-file-width=&quot;792&quot; data-file-height=&quot;499&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Demonstrators in the Darwin rebellion&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/546&quot; title=&quot;546&quot;&gt;546&lt;/a&gt; – Led by &lt;a href=&quot;/wiki/Totila&quot; title=&quot;Totila&quot;&gt;Totila&lt;/a&gt;, the &lt;a href=&quot;/wiki/Ostrogoths&quot; title=&quot;Ostrogoths&quot;&gt;Ostrogoths&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Sack_of_Rome_(546)&quot; title=&quot;Sack of Rome (546)&quot;&gt;sacked Rome&lt;/a&gt;&lt;/b&gt; after a nearly year-long siege.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1583&quot; title=&quot;1583&quot;&gt;1583&lt;/a&gt; – &lt;a href=&quot;/wiki/Cologne_War&quot; title=&quot;Cologne War&quot;&gt;Cologne War&lt;/a&gt;: Forces under &lt;a href=&quot;/wiki/Ernest_of_Bavaria&quot; title=&quot;Ernest of Bavaria&quot;&gt;Ernest of Bavaria&lt;/a&gt; defeated &lt;a href=&quot;/wiki/Gebhard_Truchsess_von_Waldburg&quot; title=&quot;Gebhard Truchsess von Waldburg&quot;&gt;Gebhard Truchsess von Waldburg&lt;/a&gt;'s troops at the &lt;b&gt;&lt;a href=&quot;/wiki/Siege_of_Godesberg&quot; title=&quot;Siege of Godesberg&quot;&gt;siege of Godesberg&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1918&quot; title=&quot;1918&quot;&gt;1918&lt;/a&gt; – About 1,000 demonstrators &lt;b&gt;&lt;a href=&quot;/wiki/Darwin_rebellion&quot; title=&quot;Darwin rebellion&quot;&gt;marched&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; on &lt;a href=&quot;/wiki/Government_House,_Darwin&quot; title=&quot;Government House, Darwin&quot;&gt;Government House&lt;/a&gt; in &lt;a href=&quot;/wiki/Darwin,_Northern_Territory&quot; title=&quot;Darwin, Northern Territory&quot;&gt;Darwin&lt;/a&gt;, Australia, where they burned an &lt;a href=&quot;/wiki/Effigy&quot; title=&quot;Effigy&quot;&gt;effigy&lt;/a&gt; of Administrator &lt;a href=&quot;/wiki/John_A._Gilruth&quot; title=&quot;John A. Gilruth&quot;&gt;John Gilruth&lt;/a&gt; and demanded his resignation.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1951&quot; title=&quot;1951&quot;&gt;1951&lt;/a&gt; – The &lt;a href=&quot;/wiki/Civil_Rights_Congress&quot; title=&quot;Civil Rights Congress&quot;&gt;Civil Rights Congress&lt;/a&gt; presented a document to the United Nations &lt;a href=&quot;/wiki/Genocide_Convention&quot; title=&quot;Genocide Convention&quot;&gt;Genocide Convention&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/We_Charge_Genocide&quot; title=&quot;We Charge Genocide&quot;&gt;charging the United States government with genocide&lt;/a&gt;&lt;/b&gt; against &lt;a href=&quot;/wiki/African_Americans&quot; title=&quot;African Americans&quot;&gt;African Americans&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1983&quot; title=&quot;1983&quot;&gt;1983&lt;/a&gt; – The &lt;a href=&quot;/wiki/Provisional_Irish_Republican_Army&quot; title=&quot;Provisional Irish Republican Army&quot;&gt;Provisional Irish Republican Army&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Harrods_bombing&quot; title=&quot;Harrods bombing&quot;&gt;detonated a car bomb&lt;/a&gt;&lt;/b&gt; just outside &lt;a href=&quot;/wiki/Harrods&quot; title=&quot;Harrods&quot;&gt;Harrods&lt;/a&gt; in London, killing six people and injuring about 90 others.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Nzinga_of_Ndongo_and_Matamba&quot; title=&quot;Nzinga of Ndongo and Matamba&quot;&gt;Nzinga of Ndongo and Matamba&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1663)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Aubrey_Faulkner&quot; title=&quot;Aubrey Faulkner&quot;&gt;Aubrey Faulkner&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1881)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Eva_Ekvall&quot; title=&quot;Eva Ekvall&quot;&gt;Eva Ekvall&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;2011)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_17&quot; title=&quot;December 17&quot;&gt;December 17&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_18&quot; title=&quot;December 18&quot;&gt;December 18&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211218000000/en</id>
		<title>On this day: December 18</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211218000000/en"/>
		<updated>2021-12-18T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_18&quot; title=&quot;December 18&quot;&gt;December 18&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/National_Day_(Qatar)&quot; title=&quot;National Day (Qatar)&quot;&gt;National Day&lt;/a&gt;&lt;/b&gt; in Qatar (&lt;a href=&quot;/wiki/1878&quot; title=&quot;1878&quot;&gt;1878&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 140px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e,_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg&quot; class=&quot;image&quot; title=&quot;Gaston de Chasseloup-Laubat&quot;&gt;&lt;img alt=&quot;Gaston de Chasseloup-Laubat&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/5/51/Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e%2C_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg/140px-Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e%2C_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg&quot; decoding=&quot;async&quot; width=&quot;140&quot; height=&quot;140&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/5/51/Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e%2C_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg/210px-Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e%2C_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/51/Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e%2C_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg/280px-Le_comte_Gaston_de_Chasseloup-Laubat_sur_Jeantaud_Duc_%C3%A9lectrique_Profil%C3%A9e%2C_recordman_de_vitesse_le_le_4_mars_1899_%C3%A0_Ach%C3%A8res.jpg 2x&quot; data-file-width=&quot;655&quot; data-file-height=&quot;656&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Gaston de Chasseloup-Laubat&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1499&quot; title=&quot;1499&quot;&gt;1499&lt;/a&gt; – Muslims in &lt;a href=&quot;/wiki/Granada&quot; title=&quot;Granada&quot;&gt;Granada&lt;/a&gt; began &lt;b&gt;&lt;a href=&quot;/wiki/Rebellion_of_the_Alpujarras_(1499%E2%80%931501)&quot; title=&quot;Rebellion of the Alpujarras (1499–1501)&quot;&gt;a rebellion&lt;/a&gt;&lt;/b&gt; against their &lt;a href=&quot;/wiki/Crown_of_Castile&quot; title=&quot;Crown of Castile&quot;&gt;Castilian&lt;/a&gt; rulers in response to &lt;a href=&quot;/wiki/Forced_conversions_of_Muslims_in_Spain&quot; title=&quot;Forced conversions of Muslims in Spain&quot;&gt;forced conversions to Catholicism&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1898&quot; title=&quot;1898&quot;&gt;1898&lt;/a&gt; – &lt;a href=&quot;/wiki/Gaston_de_Chasseloup-Laubat&quot; title=&quot;Gaston de Chasseloup-Laubat&quot;&gt;Gaston de Chasseloup-Laubat&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt; set the first official &lt;b&gt;&lt;a href=&quot;/wiki/Land_speed_record&quot; title=&quot;Land speed record&quot;&gt;land speed record&lt;/a&gt;&lt;/b&gt;, averaging 63.16&amp;#160;km/h (39.245&amp;#160;mph) over 1&amp;#160;km (0.62&amp;#160;mi) in &lt;a href=&quot;/wiki/Ach%C3%A8res,_Yvelines&quot; title=&quot;Achères, Yvelines&quot;&gt;Achères&lt;/a&gt;, France.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1916&quot; title=&quot;1916&quot;&gt;1916&lt;/a&gt; – The French &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Verdun&quot; title=&quot;Battle of Verdun&quot;&gt;defeated German forces&lt;/a&gt;&lt;/b&gt; around the city of &lt;a href=&quot;/wiki/Verdun&quot; title=&quot;Verdun&quot;&gt;Verdun-sur-Meuse&lt;/a&gt; in northeast France, ending the longest and one of the bloodiest battles in the First World War.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1996&quot; title=&quot;1996&quot;&gt;1996&lt;/a&gt; – The &lt;a href=&quot;/wiki/Oakland_Unified_School_District&quot; title=&quot;Oakland Unified School District&quot;&gt;school board of Oakland, California&lt;/a&gt;, &lt;b&gt;&lt;a href=&quot;/wiki/African-American_Vernacular_English_and_education&quot; title=&quot;African-American Vernacular English and education&quot;&gt;passed a controversial resolution&lt;/a&gt;&lt;/b&gt; officially declaring &lt;a href=&quot;/wiki/African-American_Vernacular_English&quot; title=&quot;African-American Vernacular English&quot;&gt;African-American Vernacular English&lt;/a&gt; to be a separate language or dialect.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Henrietta_Edwards&quot; title=&quot;Henrietta Edwards&quot;&gt;Henrietta Edwards&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1849)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Robert_Moses&quot; title=&quot;Robert Moses&quot;&gt;Robert Moses&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1888)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Noriko_Matsueda&quot; title=&quot;Noriko Matsueda&quot;&gt;Noriko Matsueda&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1971)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_17&quot; title=&quot;December 17&quot;&gt;December 17&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_18&quot; title=&quot;December 18&quot;&gt;December 18&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_19&quot; title=&quot;December 19&quot;&gt;December 19&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211219000000/en</id>
		<title>On this day: December 19</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211219000000/en"/>
		<updated>2021-12-19T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_19&quot; title=&quot;December 19&quot;&gt;December 19&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 129px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Andrey_Karlov_2016.jpg&quot; class=&quot;image&quot; title=&quot;Andrei Karlov&quot;&gt;&lt;img alt=&quot;Andrei Karlov&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Andrey_Karlov_2016.jpg/129px-Andrey_Karlov_2016.jpg&quot; decoding=&quot;async&quot; width=&quot;129&quot; height=&quot;152&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Andrey_Karlov_2016.jpg/194px-Andrey_Karlov_2016.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/4/4a/Andrey_Karlov_2016.jpg 2x&quot; data-file-width=&quot;251&quot; data-file-height=&quot;296&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Andrei Karlov&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1154&quot; title=&quot;1154&quot;&gt;1154&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Henry_II_of_England&quot; title=&quot;Henry II of England&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;Henry II&lt;/span&gt;&lt;/a&gt;&lt;/b&gt; was &lt;a href=&quot;/wiki/Coronation_of_the_British_monarch&quot; title=&quot;Coronation of the British monarch&quot;&gt;crowned king of England&lt;/a&gt; in &lt;a href=&quot;/wiki/Westminster_Abbey&quot; title=&quot;Westminster Abbey&quot;&gt;Westminster Abbey&lt;/a&gt;, London.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1675&quot; title=&quot;1675&quot;&gt;1675&lt;/a&gt; – &lt;a href=&quot;/wiki/King_Philip%27s_War&quot; title=&quot;King Philip&amp;#39;s War&quot;&gt;King Philip's War&lt;/a&gt;: The colonial militia of &lt;a href=&quot;/wiki/New_England_Confederation&quot; title=&quot;New England Confederation&quot;&gt;New England&lt;/a&gt; and their &lt;a href=&quot;/wiki/Pequots&quot; title=&quot;Pequots&quot;&gt;Pequot&lt;/a&gt; allies &lt;b&gt;&lt;a href=&quot;/wiki/Great_Swamp_Fight&quot; title=&quot;Great Swamp Fight&quot;&gt;attacked&lt;/a&gt;&lt;/b&gt; a &lt;a href=&quot;/wiki/Narragansett_people&quot; title=&quot;Narragansett people&quot;&gt;Narragansett&lt;/a&gt; fort in Rhode Island, killing many warriors and hundreds of non-combatants.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1956&quot; title=&quot;1956&quot;&gt;1956&lt;/a&gt; – British physician and suspected serial killer &lt;b&gt;&lt;a href=&quot;/wiki/John_Bodkin_Adams&quot; title=&quot;John Bodkin Adams&quot;&gt;John Bodkin Adams&lt;/a&gt;&lt;/b&gt; was arrested in connection with the &lt;a href=&quot;/wiki/Death_of_Edith_Alice_Morrell&quot; title=&quot;Death of Edith Alice Morrell&quot;&gt;death of Edith Alice Morrell&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1985&quot; title=&quot;1985&quot;&gt;1985&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Aeroflot_Flight_101/435&quot; title=&quot;Aeroflot Flight 101/435&quot;&gt;Aeroflot Flight 101/435&lt;/a&gt;&lt;/b&gt; was hijacked by the co-pilot and landed in a rice field in China, where he was apprehended.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2016&quot; title=&quot;2016&quot;&gt;2016&lt;/a&gt; – &lt;a href=&quot;/wiki/Andrei_Karlov&quot; title=&quot;Andrei Karlov&quot;&gt;Andrei Karlov&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt;, Russia's ambassador to Turkey, &lt;b&gt;&lt;a href=&quot;/wiki/Assassination_of_Andrei_Karlov&quot; title=&quot;Assassination of Andrei Karlov&quot;&gt;was assassinated&lt;/a&gt;&lt;/b&gt; at an art gallery in &lt;a href=&quot;/wiki/Ankara&quot; title=&quot;Ankara&quot;&gt;Ankara&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/J._M._W._Turner&quot; title=&quot;J. M. W. Turner&quot;&gt;J.&amp;#160;M.&amp;#160;W. Turner&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1851)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mileva_Mari%C4%87&quot; title=&quot;Mileva Marić&quot;&gt;Mileva Marić&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1875)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Ashfaqulla_Khan&quot; title=&quot;Ashfaqulla Khan&quot;&gt;Ashfaqulla Khan&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1927)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_18&quot; title=&quot;December 18&quot;&gt;December 18&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_19&quot; title=&quot;December 19&quot;&gt;December 19&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_20&quot; title=&quot;December 20&quot;&gt;December 20&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211220000000/en</id>
		<title>On this day: December 20</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211220000000/en"/>
		<updated>2021-12-20T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_20&quot; title=&quot;December 20&quot;&gt;December 20&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 198px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Cardiff_City_Hall_cropped.jpg&quot; class=&quot;image&quot; title=&quot;Cardiff City Hall&quot;&gt;&lt;img alt=&quot;Cardiff City Hall&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cardiff_City_Hall_cropped.jpg/198px-Cardiff_City_Hall_cropped.jpg&quot; decoding=&quot;async&quot; width=&quot;198&quot; height=&quot;99&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cardiff_City_Hall_cropped.jpg/297px-Cardiff_City_Hall_cropped.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cardiff_City_Hall_cropped.jpg/396px-Cardiff_City_Hall_cropped.jpg 2x&quot; data-file-width=&quot;2216&quot; data-file-height=&quot;1108&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Cardiff City Hall&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1955&quot; title=&quot;1955&quot;&gt;1955&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Cardiff&quot; title=&quot;Cardiff&quot;&gt;Cardiff&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(&lt;a href=&quot;/wiki/City_Hall,_Cardiff&quot; title=&quot;City Hall, Cardiff&quot;&gt;City Hall&lt;/a&gt; pictured)&lt;/i&gt; was recognised as the &lt;a href=&quot;/wiki/Capital_of_Wales&quot; title=&quot;Capital of Wales&quot;&gt;capital of Wales&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1968&quot; title=&quot;1968&quot;&gt;1968&lt;/a&gt; – The first two confirmed murders by the &lt;b&gt;&lt;a href=&quot;/wiki/Zodiac_Killer&quot; title=&quot;Zodiac Killer&quot;&gt;Zodiac Killer&lt;/a&gt;&lt;/b&gt; occurred in &lt;a href=&quot;/wiki/Benicia,_California&quot; title=&quot;Benicia, California&quot;&gt;Benicia, California&lt;/a&gt;, in a case which remains unsolved.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1988&quot; title=&quot;1988&quot;&gt;1988&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/United_Nations_Convention_Against_Illicit_Traffic_in_Narcotic_Drugs_and_Psychotropic_Substances&quot; title=&quot;United Nations Convention Against Illicit Traffic in Narcotic Drugs and Psychotropic Substances&quot;&gt;United Nations Convention Against Illicit Traffic in Narcotic Drugs and Psychotropic Substances&lt;/a&gt;&lt;/b&gt; governing international cooperation against the &lt;a href=&quot;/wiki/Illegal_drug_trade&quot; title=&quot;Illegal drug trade&quot;&gt;illegal drug trade&lt;/a&gt; was signed in &lt;a href=&quot;/wiki/Vienna&quot; title=&quot;Vienna&quot;&gt;Vienna&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1995&quot; title=&quot;1995&quot;&gt;1995&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/American_Airlines_Flight_965&quot; title=&quot;American Airlines Flight 965&quot;&gt;American Airlines Flight 965&lt;/a&gt;&lt;/b&gt; crashed into a mountain in &lt;a href=&quot;/wiki/Buga,_Valle_del_Cauca&quot; title=&quot;Buga, Valle del Cauca&quot;&gt;Buga, Colombia&lt;/a&gt;, killing 151 passengers and 8 crew members.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2007&quot; title=&quot;2007&quot;&gt;2007&lt;/a&gt; – &lt;a href=&quot;/wiki/Pablo_Picasso&quot; title=&quot;Pablo Picasso&quot;&gt;Pablo Picasso&lt;/a&gt;'s &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Portrait_of_Suzanne_Bloch&quot; title=&quot;Portrait of Suzanne Bloch&quot;&gt;Portrait of Suzanne Bloch&lt;/a&gt;&lt;/b&gt;&lt;/i&gt; was stolen from the &lt;a href=&quot;/wiki/S%C3%A3o_Paulo_Museum_of_Art&quot; title=&quot;São Paulo Museum of Art&quot;&gt;São Paulo Museum of Art&lt;/a&gt;, before being recovered about three weeks later.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/John_Bell_(farmer)&quot; title=&quot;John Bell (farmer)&quot;&gt;John Bell&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1820)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Kan%27ichi_Asakawa&quot; title=&quot;Kan&amp;#39;ichi Asakawa&quot;&gt;Kan'ichi Asakawa&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1873)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Beatrice_Beeby&quot; title=&quot;Beatrice Beeby&quot;&gt;Beatrice Beeby&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1991)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_19&quot; title=&quot;December 19&quot;&gt;December 19&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_20&quot; title=&quot;December 20&quot;&gt;December 20&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_21&quot; title=&quot;December 21&quot;&gt;December 21&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211221000000/en</id>
		<title>On this day: December 21</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211221000000/en"/>
		<updated>2021-12-21T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_21&quot; title=&quot;December 21&quot;&gt;December 21&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/December_solstice&quot; title=&quot;December solstice&quot;&gt;December solstice&lt;/a&gt;&lt;/b&gt; (15:59&amp;#160;&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;, 2021); &lt;b&gt;&lt;a href=&quot;/wiki/Yule&quot; title=&quot;Yule&quot;&gt;Yule&lt;/a&gt;&lt;/b&gt; begins
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 162px;&quot;&gt;
&lt;a href=&quot;/wiki/File:ToadLane2009.jpg&quot; class=&quot;image&quot; title=&quot;The Rochdale Pioneers&amp;#39; first store&quot;&gt;&lt;img alt=&quot;The Rochdale Pioneers&amp;#39; first store&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/76/ToadLane2009.jpg/162px-ToadLane2009.jpg&quot; decoding=&quot;async&quot; width=&quot;162&quot; height=&quot;122&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/76/ToadLane2009.jpg/243px-ToadLane2009.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/76/ToadLane2009.jpg/324px-ToadLane2009.jpg 2x&quot; data-file-width=&quot;3664&quot; data-file-height=&quot;2748&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;The Rochdale Pioneers' first store&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1826&quot; title=&quot;1826&quot;&gt;1826&lt;/a&gt; – Settlers from the United States in &lt;a href=&quot;/wiki/Mexican_Texas&quot; title=&quot;Mexican Texas&quot;&gt;Mexican Texas&lt;/a&gt; made the first attempt to secede from Mexico, establishing the short-lived &lt;b&gt;&lt;a href=&quot;/wiki/Fredonian_Rebellion&quot; title=&quot;Fredonian Rebellion&quot;&gt;Republic of Fredonia&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1844&quot; title=&quot;1844&quot;&gt;1844&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Rochdale_Society_of_Equitable_Pioneers&quot; title=&quot;Rochdale Society of Equitable Pioneers&quot;&gt;Rochdale Pioneers&lt;/a&gt;&lt;/b&gt; opened their store &lt;i&gt;(pictured)&lt;/i&gt; in &lt;a href=&quot;/wiki/Rochdale&quot; title=&quot;Rochdale&quot;&gt;Rochdale&lt;/a&gt;, England, &lt;a href=&quot;/wiki/History_of_the_cooperative_movement&quot; title=&quot;History of the cooperative movement&quot;&gt;forming the basis for the modern co-operative movement&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1923&quot; title=&quot;1923&quot;&gt;1923&lt;/a&gt; – Nepal and the United Kingdom signed &lt;b&gt;&lt;a href=&quot;/wiki/Nepal%E2%80%93Britain_Treaty_of_1923&quot; title=&quot;Nepal–Britain Treaty of 1923&quot;&gt;the first treaty that defined the international status of Nepal&lt;/a&gt;&lt;/b&gt; as an independent and a sovereign nation.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1965&quot; title=&quot;1965&quot;&gt;1965&lt;/a&gt; – The &lt;a href=&quot;/wiki/United_Nations&quot; title=&quot;United Nations&quot;&gt;United Nations&lt;/a&gt; adopted the &lt;b&gt;&lt;a href=&quot;/wiki/International_Convention_on_the_Elimination_of_All_Forms_of_Racial_Discrimination&quot; title=&quot;International Convention on the Elimination of All Forms of Racial Discrimination&quot;&gt;International Convention on the Elimination of All Forms of Racial Discrimination&lt;/a&gt;&lt;/b&gt;, which 88 member states have since signed.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1988&quot; title=&quot;1988&quot;&gt;1988&lt;/a&gt; – The world's largest aircraft, the &lt;b&gt;&lt;a href=&quot;/wiki/Antonov_An-225_Mriya&quot; title=&quot;Antonov An-225 Mriya&quot;&gt;Antonov &lt;span class=&quot;nowrap&quot;&gt;An-225&lt;/span&gt; &lt;i&gt;Mriya&lt;/i&gt;&lt;/a&gt;&lt;/b&gt;, made its first flight.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Hugh,_Margrave_of_Tuscany&quot; title=&quot;Hugh, Margrave of Tuscany&quot;&gt;Hugh, Margrave of Tuscany&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1001)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/William_H._Osborn&quot; title=&quot;William H. Osborn&quot;&gt;William H. Osborn&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1820)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Adele_Goldstine&quot; title=&quot;Adele Goldstine&quot;&gt;Adele Goldstine&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1920)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_20&quot; title=&quot;December 20&quot;&gt;December 20&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_21&quot; title=&quot;December 21&quot;&gt;December 21&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_22&quot; title=&quot;December 22&quot;&gt;December 22&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
</feed>