<?xml version="1.0"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
	<id>https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom</id>
	<title>Wikipedia &quot;On this day...&quot; feed</title>
	<link rel="self" type="application/atom+xml" href="https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom"/>
	<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Main_Page"/>
	<updated>2021-11-25T20:47:28Z</updated>
	<subtitle>Historical events on this day</subtitle>
	<generator>MediaWiki 1.38.0-wmf.9</generator>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211116000000/en</id>
		<title>On this day: November 16</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211116000000/en"/>
		<updated>2021-11-16T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_16&quot; title=&quot;November 16&quot;&gt;November 16&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 114px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg&quot; class=&quot;image&quot; title=&quot;Wei Jingsheng&quot;&gt;&lt;img alt=&quot;Wei Jingsheng&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg/114px-Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg&quot; decoding=&quot;async&quot; width=&quot;114&quot; height=&quot;171&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg/171px-Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg/228px-Wei_Jingsheng_par_Claude_Truong-Ngoc_novembre_2013.jpg 2x&quot; data-file-width=&quot;3840&quot; data-file-height=&quot;5760&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Wei Jingsheng&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/534&quot; title=&quot;534&quot;&gt;534&lt;/a&gt; – The second edition of the &lt;b&gt;&lt;a href=&quot;/wiki/Code_of_Justinian&quot; title=&quot;Code of Justinian&quot;&gt;Code of Justinian&lt;/a&gt;&lt;/b&gt;, a codification of &lt;a href=&quot;/wiki/Roman_law&quot; title=&quot;Roman law&quot;&gt;Roman law&lt;/a&gt; by Byzantine emperor &lt;a href=&quot;/wiki/Justinian_I&quot; title=&quot;Justinian I&quot;&gt;Justinian&amp;#160;I&lt;/a&gt;, was published.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1776&quot; title=&quot;1776&quot;&gt;1776&lt;/a&gt; – &lt;a href=&quot;/wiki/American_Revolutionary_War&quot; title=&quot;American Revolutionary War&quot;&gt;American Revolutionary War&lt;/a&gt;: British and &lt;a href=&quot;/wiki/Hessian_(soldier)&quot; title=&quot;Hessian (soldier)&quot;&gt;Hessian&lt;/a&gt; units &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Fort_Washington&quot; title=&quot;Battle of Fort Washington&quot;&gt;captured&lt;/a&gt;&lt;/b&gt; &lt;a href=&quot;/wiki/Fort_Washington_(Manhattan)&quot; title=&quot;Fort Washington (Manhattan)&quot;&gt;Fort Washington&lt;/a&gt; on &lt;a href=&quot;/wiki/Manhattan&quot; title=&quot;Manhattan&quot;&gt;Manhattan&lt;/a&gt; from the &lt;a href=&quot;/wiki/Patriot_(American_Revolution)&quot; title=&quot;Patriot (American Revolution)&quot;&gt;Patriots&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1938&quot; title=&quot;1938&quot;&gt;1938&lt;/a&gt; – Swiss chemist &lt;b&gt;&lt;a href=&quot;/wiki/Albert_Hofmann&quot; title=&quot;Albert Hofmann&quot;&gt;Albert Hofmann&lt;/a&gt;&lt;/b&gt; first synthesized the &lt;a href=&quot;/wiki/Psychedelic_drug&quot; title=&quot;Psychedelic drug&quot;&gt;psychedelic&lt;/a&gt; drug &lt;a href=&quot;/wiki/Lysergic_acid_diethylamide&quot; title=&quot;Lysergic acid diethylamide&quot;&gt;LSD&lt;/a&gt; in &lt;a href=&quot;/wiki/Basel&quot; title=&quot;Basel&quot;&gt;Basel&lt;/a&gt;, Switzerland.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1981&quot; title=&quot;1981&quot;&gt;1981&lt;/a&gt; – About 30&amp;#160;million people watched the fictional couple &lt;b&gt;&lt;a href=&quot;/wiki/Luke_and_Laura&quot; title=&quot;Luke and Laura&quot;&gt;Luke Spencer and Laura Webber&lt;/a&gt;&lt;/b&gt; marry on the television show &lt;i&gt;&lt;a href=&quot;/wiki/General_Hospital&quot; title=&quot;General Hospital&quot;&gt;General Hospital&lt;/a&gt;&lt;/i&gt; in the highest-rated hour in American &lt;a href=&quot;/wiki/Soap_opera&quot; title=&quot;Soap opera&quot;&gt;soap opera&lt;/a&gt; history.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1997&quot; title=&quot;1997&quot;&gt;1997&lt;/a&gt; – &lt;a href=&quot;/wiki/List_of_Chinese_dissidents&quot; title=&quot;List of Chinese dissidents&quot;&gt;Chinese dissident&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wei_Jingsheng&quot; title=&quot;Wei Jingsheng&quot;&gt;Wei Jingsheng&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; was released for &quot;medical reasons&quot; after spending seventeen and a half of the previous eighteen years in prison, and was deported to the United States.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Nasr_of_Granada&quot; title=&quot;Nasr of Granada&quot;&gt;Nasr of Granada&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1322)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Eleanor_Coade&quot; title=&quot;Eleanor Coade&quot;&gt;Eleanor Coade&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1821)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Panditrao_Agashe&quot; title=&quot;Panditrao Agashe&quot;&gt;Panditrao Agashe&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1986)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt; 
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_15&quot; title=&quot;November 15&quot;&gt;November 15&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_16&quot; title=&quot;November 16&quot;&gt;November 16&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_17&quot; title=&quot;November 17&quot;&gt;November 17&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211117000000/en</id>
		<title>On this day: November 17</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211117000000/en"/>
		<updated>2021-11-17T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_17&quot; title=&quot;November 17&quot;&gt;November 17&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 121px;&quot;&gt;
&lt;a href=&quot;/wiki/File:MK37723_Tenzin_Gyatso.jpg&quot; class=&quot;image&quot; title=&quot;14th Dalai Lama&quot;&gt;&lt;img alt=&quot;14th Dalai Lama&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/4/41/MK37723_Tenzin_Gyatso.jpg/121px-MK37723_Tenzin_Gyatso.jpg&quot; decoding=&quot;async&quot; width=&quot;121&quot; height=&quot;161&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/4/41/MK37723_Tenzin_Gyatso.jpg/182px-MK37723_Tenzin_Gyatso.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/41/MK37723_Tenzin_Gyatso.jpg/242px-MK37723_Tenzin_Gyatso.jpg 2x&quot; data-file-width=&quot;1936&quot; data-file-height=&quot;2581&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;14th Dalai Lama&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1796&quot; title=&quot;1796&quot;&gt;1796&lt;/a&gt; – &lt;a href=&quot;/wiki/French_Revolutionary_Wars&quot; title=&quot;French Revolutionary Wars&quot;&gt;French Revolutionary Wars&lt;/a&gt;: French forces defeated the &lt;a href=&quot;/wiki/Habsburg_Monarchy&quot; title=&quot;Habsburg Monarchy&quot;&gt;Austrians&lt;/a&gt; at the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Arcole&quot; title=&quot;Battle of Arcole&quot;&gt;Battle of Arcole&lt;/a&gt;&lt;/b&gt; in a manoeuvre to cut the latter's line of retreat.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1950&quot; title=&quot;1950&quot;&gt;1950&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/14th_Dalai_Lama&quot; title=&quot;14th Dalai Lama&quot;&gt;14th Dalai Lama&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; assumed full temporal power as ruler of &lt;a href=&quot;/wiki/Tibet&quot; title=&quot;Tibet&quot;&gt;Tibet&lt;/a&gt; at the age of fifteen.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1968&quot; title=&quot;1968&quot;&gt;1968&lt;/a&gt; – &lt;a href=&quot;/wiki/NBC&quot; title=&quot;NBC&quot;&gt;NBC&lt;/a&gt; controversially &lt;b&gt;&lt;a href=&quot;/wiki/Heidi_Game&quot; title=&quot;Heidi Game&quot;&gt;cut away&lt;/a&gt;&lt;/b&gt; from an American football game between the &lt;a href=&quot;/wiki/History_of_the_Oakland_Raiders&quot; title=&quot;History of the Oakland Raiders&quot;&gt;Oakland Raiders&lt;/a&gt; and &lt;a href=&quot;/wiki/New_York_Jets&quot; title=&quot;New York Jets&quot;&gt;New York Jets&lt;/a&gt; to broadcast &lt;i&gt;&lt;a href=&quot;/wiki/Heidi_(1968_film)&quot; title=&quot;Heidi (1968 film)&quot;&gt;Heidi&lt;/a&gt;&lt;/i&gt;, causing viewers in the &lt;a href=&quot;/wiki/Eastern_United_States&quot; title=&quot;Eastern United States&quot;&gt;Eastern United States&lt;/a&gt; to miss the game's dramatic ending.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2009&quot; title=&quot;2009&quot;&gt;2009&lt;/a&gt; – Administrators at the &lt;a href=&quot;/wiki/University_of_East_Anglia&quot; title=&quot;University of East Anglia&quot;&gt;University of East Anglia&lt;/a&gt;'s &lt;a href=&quot;/wiki/Climatic_Research_Unit&quot; title=&quot;Climatic Research Unit&quot;&gt;Climatic Research Unit&lt;/a&gt; discovered that their servers had been &lt;a href=&quot;/wiki/Security_hacker&quot; title=&quot;Security hacker&quot;&gt;hacked&lt;/a&gt; and thousands of emails and files on &lt;a href=&quot;/wiki/Climate_change&quot; title=&quot;Climate change&quot;&gt;climate change&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Climatic_Research_Unit_email_controversy&quot; title=&quot;Climatic Research Unit email controversy&quot;&gt;had been stolen&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Nikephoros_Melissenos&quot; title=&quot;Nikephoros Melissenos&quot;&gt;Nikephoros Melissenos&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1104)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Charlotte_of_Mecklenburg-Strelitz&quot; title=&quot;Charlotte of Mecklenburg-Strelitz&quot;&gt;Charlotte of Mecklenburg-Strelitz&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1818)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Petra_Burka&quot; title=&quot;Petra Burka&quot;&gt;Petra Burka&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1946)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_16&quot; title=&quot;November 16&quot;&gt;November 16&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_17&quot; title=&quot;November 17&quot;&gt;November 17&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_18&quot; title=&quot;November 18&quot;&gt;November 18&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211118000000/en</id>
		<title>On this day: November 18</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211118000000/en"/>
		<updated>2021-11-18T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_18&quot; title=&quot;November 18&quot;&gt;November 18&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 121px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Mark_Twain_by_Abdullah_Fr%C3%A8res,_1867.jpg&quot; class=&quot;image&quot; title=&quot;Mark Twain in 1867&quot;&gt;&lt;img alt=&quot;Mark Twain in 1867&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Mark_Twain_by_Abdullah_Fr%C3%A8res%2C_1867.jpg/121px-Mark_Twain_by_Abdullah_Fr%C3%A8res%2C_1867.jpg&quot; decoding=&quot;async&quot; width=&quot;121&quot; height=&quot;161&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Mark_Twain_by_Abdullah_Fr%C3%A8res%2C_1867.jpg/182px-Mark_Twain_by_Abdullah_Fr%C3%A8res%2C_1867.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Mark_Twain_by_Abdullah_Fr%C3%A8res%2C_1867.jpg/242px-Mark_Twain_by_Abdullah_Fr%C3%A8res%2C_1867.jpg 2x&quot; data-file-width=&quot;1101&quot; data-file-height=&quot;1468&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Mark Twain in 1867&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1210&quot; title=&quot;1210&quot;&gt;1210&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Otto_IV,_Holy_Roman_Emperor&quot; title=&quot;Otto IV, Holy Roman Emperor&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;Otto IV&lt;/span&gt;&lt;/a&gt;&lt;/b&gt;, &lt;a href=&quot;/wiki/Holy_Roman_Emperor&quot; title=&quot;Holy Roman Emperor&quot;&gt;Holy Roman Emperor&lt;/a&gt;, was &lt;a href=&quot;/wiki/Excommunication&quot; title=&quot;Excommunication&quot;&gt;ex&amp;#173;com&amp;#173;mu&amp;#173;ni&amp;#173;cated&lt;/a&gt; by &lt;a href=&quot;/wiki/Pope_Innocent_III&quot; title=&quot;Pope Innocent III&quot;&gt;Pope &lt;span class=&quot;nowrap&quot;&gt;Innocent III&lt;/span&gt;&lt;/a&gt; after Otto commanded him to annul the &lt;a href=&quot;/wiki/Investiture_Controversy#Concordat_of_Worms&quot; title=&quot;Investiture Controversy&quot;&gt;Concordat of Worms&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1865&quot; title=&quot;1865&quot;&gt;1865&lt;/a&gt; – &quot;&lt;b&gt;&lt;a href=&quot;/wiki/The_Celebrated_Jumping_Frog_of_Calaveras_County&quot; title=&quot;The Celebrated Jumping Frog of Calaveras County&quot;&gt;The Celebrated Jumping Frog of Calaveras County&lt;/a&gt;&lt;/b&gt;&quot; was published, becoming the first great success of American author &lt;a href=&quot;/wiki/Mark_Twain&quot; title=&quot;Mark Twain&quot;&gt;Mark Twain&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1956&quot; title=&quot;1956&quot;&gt;1956&lt;/a&gt; – At the Polish embassy in Moscow, Soviet leader &lt;a href=&quot;/wiki/Nikita_Khrushchev&quot; title=&quot;Nikita Khrushchev&quot;&gt;Nikita Khrushchev&lt;/a&gt; said &quot;&lt;b&gt;&lt;a href=&quot;/wiki/We_will_bury_you&quot; title=&quot;We will bury you&quot;&gt;We will bury you&lt;/a&gt;&lt;/b&gt;&quot; while addressing Western envoys, prompting them to leave the room.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1991&quot; title=&quot;1991&quot;&gt;1991&lt;/a&gt; – &lt;a href=&quot;/wiki/Croatian_War_of_Independence&quot; title=&quot;Croatian War of Independence&quot;&gt;Croatian War of Independence&lt;/a&gt;: The &lt;a href=&quot;/wiki/Yugoslav_People%27s_Army&quot; title=&quot;Yugoslav People&amp;#39;s Army&quot;&gt;Yugoslav People's Army&lt;/a&gt; captured the Croatian city of &lt;a href=&quot;/wiki/Vukovar&quot; title=&quot;Vukovar&quot;&gt;Vukovar&lt;/a&gt;, ending &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Vukovar&quot; title=&quot;Battle of Vukovar&quot;&gt;an 87-day siege&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2014&quot; title=&quot;2014&quot;&gt;2014&lt;/a&gt; – Two Palestinian men &lt;b&gt;&lt;a href=&quot;/wiki/2014_Jerusalem_synagogue_attack&quot; title=&quot;2014 Jerusalem synagogue attack&quot;&gt;attacked&lt;/a&gt;&lt;/b&gt; the praying congregants of a synagogue in Jerusalem with axes, knives, and a gun, resulting in eight deaths, including the attackers themselves.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Thomas_Burgess_(bishop_of_Salisbury)&quot; title=&quot;Thomas Burgess (bishop of Salisbury)&quot;&gt;Thomas Burgess&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1756)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Dorothy_Dix&quot; title=&quot;Dorothy Dix&quot;&gt;Dorothy Dix&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1861)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Tara_Singh_Hayer&quot; title=&quot;Tara Singh Hayer&quot;&gt;Tara Singh Hayer&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1998)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_17&quot; title=&quot;November 17&quot;&gt;November 17&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_18&quot; title=&quot;November 18&quot;&gt;November 18&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_19&quot; title=&quot;November 19&quot;&gt;November 19&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211119000000/en</id>
		<title>On this day: November 19</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211119000000/en"/>
		<updated>2021-11-19T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_19&quot; title=&quot;November 19&quot;&gt;November 19&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/International_Men%27s_Day&quot; title=&quot;International Men&amp;#39;s Day&quot;&gt;International Men's Day&lt;/a&gt;&lt;/b&gt;; &lt;b&gt;&lt;a href=&quot;/wiki/World_Toilet_Day&quot; title=&quot;World Toilet Day&quot;&gt;World Toilet Day&lt;/a&gt;&lt;/b&gt;; &lt;a href=&quot;/wiki/Liberation_Day&quot; title=&quot;Liberation Day&quot;&gt;Liberation Day&lt;/a&gt; in &lt;b&gt;&lt;a href=&quot;/wiki/Mali&quot; title=&quot;Mali&quot;&gt;Mali&lt;/a&gt;&lt;/b&gt; (&lt;a href=&quot;/wiki/1968&quot; title=&quot;1968&quot;&gt;1968&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 154px;&quot;&gt;
&lt;a href=&quot;/wiki/File:The_Mayflower_at_sea.jpg&quot; class=&quot;image&quot; title=&quot;Mayflower&quot;&gt;&lt;img alt=&quot;Mayflower&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/1/1c/The_Mayflower_at_sea.jpg/154px-The_Mayflower_at_sea.jpg&quot; decoding=&quot;async&quot; width=&quot;154&quot; height=&quot;127&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/1/1c/The_Mayflower_at_sea.jpg/231px-The_Mayflower_at_sea.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1c/The_Mayflower_at_sea.jpg/308px-The_Mayflower_at_sea.jpg 2x&quot; data-file-width=&quot;2192&quot; data-file-height=&quot;1802&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;&lt;i&gt;Mayflower&lt;/i&gt;&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1620&quot; title=&quot;1620&quot;&gt;1620&lt;/a&gt; – The &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mayflower&quot; title=&quot;Mayflower&quot;&gt;Mayflower&lt;/a&gt;&lt;/b&gt;&lt;/i&gt; &lt;i&gt;(depicted)&lt;/i&gt;, which brought the &lt;a href=&quot;/wiki/Pilgrims_(Plymouth_Colony)&quot; title=&quot;Pilgrims (Plymouth Colony)&quot;&gt;Pilgrims&lt;/a&gt; from England to the New World, sighted &lt;a href=&quot;/wiki/Cape_Cod&quot; title=&quot;Cape Cod&quot;&gt;Cape Cod&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – &lt;a href=&quot;/wiki/World_War_II&quot; title=&quot;World War II&quot;&gt;World War&amp;#160;II&lt;/a&gt;: The Australian light cruiser &lt;a href=&quot;/wiki/HMAS_Sydney_(D48)&quot; title=&quot;HMAS Sydney (D48)&quot;&gt;HMAS&amp;#160;&lt;i&gt;Sydney&lt;/i&gt;&lt;/a&gt; and the German auxiliary cruiser &lt;i&gt;&lt;a href=&quot;/wiki/German_auxiliary_cruiser_Kormoran&quot; title=&quot;German auxiliary cruiser Kormoran&quot;&gt;Kormoran&lt;/a&gt;&lt;/i&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Battle_between_HMAS_Sydney_and_German_auxiliary_cruiser_Kormoran&quot; title=&quot;Battle between HMAS Sydney and German auxiliary cruiser Kormoran&quot;&gt;destroyed each other&lt;/a&gt;&lt;/b&gt; in the Indian Ocean.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1969&quot; title=&quot;1969&quot;&gt;1969&lt;/a&gt; – Playing for &lt;a href=&quot;/wiki/Santos_FC&quot; title=&quot;Santos FC&quot;&gt;Santos&lt;/a&gt; against &lt;a href=&quot;/wiki/CR_Vasco_da_Gama&quot; title=&quot;CR Vasco da Gama&quot;&gt;Vasco da Gama&lt;/a&gt; in Rio de Janeiro, Brazilian footballer &lt;b&gt;&lt;a href=&quot;/wiki/Pel%C3%A9&quot; title=&quot;Pelé&quot;&gt;Pelé&lt;/a&gt;&lt;/b&gt; scored his thousandth goal.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1991&quot; title=&quot;1991&quot;&gt;1991&lt;/a&gt; – Mexican singer &lt;a href=&quot;/wiki/Luis_Miguel&quot; title=&quot;Luis Miguel&quot;&gt;Luis Miguel&lt;/a&gt; released his album &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Romance_(Luis_Miguel_album)&quot; title=&quot;Romance (Luis Miguel album)&quot;&gt;Romance&lt;/a&gt;&lt;/b&gt;&lt;/i&gt;, which led to the revival of interest in &lt;a href=&quot;/wiki/Bolero&quot; title=&quot;Bolero&quot;&gt;bolero&lt;/a&gt; music.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2004&quot; title=&quot;2004&quot;&gt;2004&lt;/a&gt; – During a &lt;a href=&quot;/wiki/National_Basketball_Association&quot; title=&quot;National Basketball Association&quot;&gt;NBA&lt;/a&gt; game between the &lt;a href=&quot;/wiki/Indiana_Pacers&quot; title=&quot;Indiana Pacers&quot;&gt;Indiana Pacers&lt;/a&gt; and the &lt;a href=&quot;/wiki/Detroit_Pistons&quot; title=&quot;Detroit Pistons&quot;&gt;Detroit Pistons&lt;/a&gt;, &lt;b&gt;&lt;a href=&quot;/wiki/The_Malice_at_the_Palace&quot; title=&quot;The Malice at the Palace&quot;&gt;a brawl between players&lt;/a&gt;&lt;/b&gt; spilled into the crowd when &lt;a href=&quot;/wiki/Metta_Sandiford-Artest&quot; title=&quot;Metta Sandiford-Artest&quot;&gt;Ron Artest&lt;/a&gt; attacked a fan who had thrown a drink at him.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mikhail_Kalinin&quot; title=&quot;Mikhail Kalinin&quot;&gt;Mikhail Kalinin&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1875)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Xu_Zhimo&quot; title=&quot;Xu Zhimo&quot;&gt;Xu Zhimo&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1931)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Ted_Fujita&quot; title=&quot;Ted Fujita&quot;&gt;Ted Fujita&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1998)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_18&quot; title=&quot;November 18&quot;&gt;November 18&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_19&quot; title=&quot;November 19&quot;&gt;November 19&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_20&quot; title=&quot;November 20&quot;&gt;November 20&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211120000000/en</id>
		<title>On this day: November 20</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211120000000/en"/>
		<updated>2021-11-20T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_20&quot; title=&quot;November 20&quot;&gt;November 20&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Transgender_Day_of_Remembrance&quot; title=&quot;Transgender Day of Remembrance&quot;&gt;Transgender Day of Remembrance&lt;/a&gt;&lt;/b&gt;; &lt;b&gt;&lt;a href=&quot;/wiki/National_Sovereignty_Day&quot; title=&quot;National Sovereignty Day&quot;&gt;National Sovereignty Day&lt;/a&gt;&lt;/b&gt; in Argentina (&lt;a href=&quot;/wiki/1845&quot; title=&quot;1845&quot;&gt;1845&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 117px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Asia_minore_romana,_testa_di_statua_togata_di_diocleziano,_295-300_ca.jpg&quot; class=&quot;image&quot; title=&quot;Bust of Diocletian&quot;&gt;&lt;img alt=&quot;Bust of Diocletian&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Asia_minore_romana%2C_testa_di_statua_togata_di_diocleziano%2C_295-300_ca.jpg/117px-Asia_minore_romana%2C_testa_di_statua_togata_di_diocleziano%2C_295-300_ca.jpg&quot; decoding=&quot;async&quot; width=&quot;117&quot; height=&quot;168&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Asia_minore_romana%2C_testa_di_statua_togata_di_diocleziano%2C_295-300_ca.jpg/176px-Asia_minore_romana%2C_testa_di_statua_togata_di_diocleziano%2C_295-300_ca.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Asia_minore_romana%2C_testa_di_statua_togata_di_diocleziano%2C_295-300_ca.jpg/234px-Asia_minore_romana%2C_testa_di_statua_togata_di_diocleziano%2C_295-300_ca.jpg 2x&quot; data-file-width=&quot;1552&quot; data-file-height=&quot;2228&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Bust of Diocletian&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/284&quot; title=&quot;284&quot;&gt;284&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Diocletian&quot; title=&quot;Diocletian&quot;&gt;Diocletian&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(bust pictured)&lt;/i&gt; became &lt;a href=&quot;/wiki/Roman_emperor&quot; title=&quot;Roman emperor&quot;&gt;Roman emperor&lt;/a&gt;, eventually establishing reforms that ended the &lt;a href=&quot;/wiki/Crisis_of_the_Third_Century&quot; title=&quot;Crisis of the Third Century&quot;&gt;Crisis of the Third Century&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1739&quot; title=&quot;1739&quot;&gt;1739&lt;/a&gt; – &lt;a href=&quot;/wiki/War_of_Jenkins%27_Ear&quot; title=&quot;War of Jenkins&amp;#39; Ear&quot;&gt;War of Jenkins' Ear&lt;/a&gt;: A British naval force &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Porto_Bello_(1739)&quot; title=&quot;Battle of Porto Bello (1739)&quot;&gt;arrived&lt;/a&gt;&lt;/b&gt; at the settlement of &lt;a href=&quot;/wiki/Portobelo,_Col%C3%B3n&quot; title=&quot;Portobelo, Colón&quot;&gt;Portobello&lt;/a&gt; in the &lt;a href=&quot;/wiki/Spanish_Main&quot; title=&quot;Spanish Main&quot;&gt;Spanish Main&lt;/a&gt; (now in Panama), which it captured the next day.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1902&quot; title=&quot;1902&quot;&gt;1902&lt;/a&gt; – While discussing how to promote the newspaper &lt;i&gt;&lt;a href=&quot;/wiki/L%27%C3%89quipe&quot; title=&quot;L&amp;#39;Équipe&quot;&gt;L'Auto&lt;/a&gt;&lt;/i&gt;, sports journalist &lt;a href=&quot;/wiki/G%C3%A9o_Lef%C3%A8vre&quot; title=&quot;Géo Lefèvre&quot;&gt;Géo Lefèvre&lt;/a&gt; came up with the idea of holding a &lt;a href=&quot;/wiki/Road_bicycle_racing&quot; title=&quot;Road bicycle racing&quot;&gt;cycling race&lt;/a&gt; that later became known as the &lt;b&gt;&lt;a href=&quot;/wiki/Tour_de_France&quot; title=&quot;Tour de France&quot;&gt;Tour de France&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1979&quot; title=&quot;1979&quot;&gt;1979&lt;/a&gt; – A group of armed insurgents &lt;b&gt;&lt;a href=&quot;/wiki/Grand_Mosque_seizure&quot; title=&quot;Grand Mosque seizure&quot;&gt;attacked and took over&lt;/a&gt;&lt;/b&gt; the &lt;a href=&quot;/wiki/Masjid_al-Haram&quot; title=&quot;Masjid al-Haram&quot;&gt;Masjid al-Haram&lt;/a&gt; in &lt;a href=&quot;/wiki/Mecca&quot; title=&quot;Mecca&quot;&gt;Mecca&lt;/a&gt;, declaring that one of their leaders was the &lt;a href=&quot;/wiki/Mahdi&quot; title=&quot;Mahdi&quot;&gt;Mahdi&lt;/a&gt;, the prophesied redeemer of Islam.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1991&quot; title=&quot;1991&quot;&gt;1991&lt;/a&gt; – &lt;a href=&quot;/wiki/First_Nagorno-Karabakh_War&quot; title=&quot;First Nagorno-Karabakh War&quot;&gt;First Nagorno-Karabakh War&lt;/a&gt;: An Azerbaijani military helicopter carrying a peacekeeping mission team &lt;b&gt;&lt;a href=&quot;/wiki/1991_Azerbaijani_Mil_Mi-8_shootdown&quot; title=&quot;1991 Azerbaijani Mil Mi-8 shootdown&quot;&gt;was shot down&lt;/a&gt;&lt;/b&gt; in &lt;a href=&quot;/wiki/Nagorno-Karabakh&quot; title=&quot;Nagorno-Karabakh&quot;&gt;Nagorno-Karabakh&lt;/a&gt;, Azerbaijan, disrupting the ongoing peace talks.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Thomas_Chatterton&quot; title=&quot;Thomas Chatterton&quot;&gt;Thomas Chatterton&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1752)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Irakli_Tsereteli&quot; title=&quot;Irakli Tsereteli&quot;&gt;Irakli Tsereteli&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1881)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Ancel_Keys&quot; title=&quot;Ancel Keys&quot;&gt;Ancel Keys&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;2004)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_19&quot; title=&quot;November 19&quot;&gt;November 19&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_20&quot; title=&quot;November 20&quot;&gt;November 20&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_21&quot; title=&quot;November 21&quot;&gt;November 21&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211121000000/en</id>
		<title>On this day: November 21</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211121000000/en"/>
		<updated>2021-11-21T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_21&quot; title=&quot;November 21&quot;&gt;November 21&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Armed_Forces_Day_(Bangladesh)&quot; title=&quot;Armed Forces Day (Bangladesh)&quot;&gt;Armed Forces Day&lt;/a&gt;&lt;/b&gt; in Bangladesh
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 127px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Alan_Freed_disk_jockey.jpg&quot; class=&quot;image&quot; title=&quot;Alan Freed&quot;&gt;&lt;img alt=&quot;Alan Freed&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Alan_Freed_disk_jockey.jpg/127px-Alan_Freed_disk_jockey.jpg&quot; decoding=&quot;async&quot; width=&quot;127&quot; height=&quot;153&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Alan_Freed_disk_jockey.jpg/191px-Alan_Freed_disk_jockey.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Alan_Freed_disk_jockey.jpg/254px-Alan_Freed_disk_jockey.jpg 2x&quot; data-file-width=&quot;655&quot; data-file-height=&quot;791&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Alan Freed&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1386&quot; title=&quot;1386&quot;&gt;1386&lt;/a&gt; – &lt;a href=&quot;/wiki/Turco-Mongol_tradition&quot; title=&quot;Turco-Mongol tradition&quot;&gt;Turco-Mongol&lt;/a&gt; conqueror &lt;a href=&quot;/wiki/Timur&quot; title=&quot;Timur&quot;&gt;Timur&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Timur%27s_invasions_of_Georgia&quot; title=&quot;Timur&amp;#39;s invasions of Georgia&quot;&gt;captured and sacked&lt;/a&gt;&lt;/b&gt; the &lt;a href=&quot;/wiki/Kingdom_of_Georgia&quot; title=&quot;Kingdom of Georgia&quot;&gt;Georgian&lt;/a&gt; capital &lt;a href=&quot;/wiki/Tbilisi&quot; title=&quot;Tbilisi&quot;&gt;Tbilisi&lt;/a&gt; and forced King &lt;a href=&quot;/wiki/Bagrat_V_of_Georgia&quot; title=&quot;Bagrat V of Georgia&quot;&gt;Bagrat&amp;#160;V&lt;/a&gt; to convert to Islam.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1894&quot; title=&quot;1894&quot;&gt;1894&lt;/a&gt; – &lt;a href=&quot;/wiki/First_Sino-Japanese_War&quot; title=&quot;First Sino-Japanese War&quot;&gt;First Sino-Japanese War&lt;/a&gt;: After &lt;a href=&quot;/wiki/Battle_of_L%C3%BCshunkou&quot; title=&quot;Battle of Lüshunkou&quot;&gt;capturing&lt;/a&gt; the Chinese city of &lt;a href=&quot;/wiki/L%C3%BCshunkou_District&quot; title=&quot;Lüshunkou District&quot;&gt;Port Arthur&lt;/a&gt;, the Japanese army began &lt;b&gt;&lt;a href=&quot;/wiki/Port_Arthur_massacre_(China)&quot; title=&quot;Port Arthur massacre (China)&quot;&gt;a massacre of the city's soldiers and civilians&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1959&quot; title=&quot;1959&quot;&gt;1959&lt;/a&gt; – American &lt;a href=&quot;/wiki/Disc_jockey&quot; title=&quot;Disc jockey&quot;&gt;disc jockey&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Alan_Freed&quot; title=&quot;Alan Freed&quot;&gt;Alan Freed&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt;, who popularized the term &lt;i&gt;&lt;a href=&quot;/wiki/Rock_and_roll&quot; title=&quot;Rock and roll&quot;&gt;rock and roll&lt;/a&gt;&lt;/i&gt;, was fired from &lt;a href=&quot;/wiki/WABC_(AM)&quot; title=&quot;WABC (AM)&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;WABC-AM&lt;/span&gt;&lt;/a&gt; for his role in the &lt;a href=&quot;/wiki/Payola&quot; title=&quot;Payola&quot;&gt;payola&lt;/a&gt; scandal.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1974&quot; title=&quot;1974&quot;&gt;1974&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Birmingham_pub_bombings&quot; title=&quot;Birmingham pub bombings&quot;&gt;Bombs exploded&lt;/a&gt;&lt;/b&gt; in two &lt;a href=&quot;/wiki/Pub&quot; title=&quot;Pub&quot;&gt;pubs&lt;/a&gt; in central &lt;a href=&quot;/wiki/Birmingham&quot; title=&quot;Birmingham&quot;&gt;Birmingham&lt;/a&gt;, England, killing 21 people and leading to the imprisonment of &lt;a href=&quot;/wiki/Birmingham_Six&quot; title=&quot;Birmingham Six&quot;&gt;six people who were later exonerated&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2009&quot; title=&quot;2009&quot;&gt;2009&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/2009_Heilongjiang_mine_explosion&quot; title=&quot;2009 Heilongjiang mine explosion&quot;&gt;An explosion&lt;/a&gt;&lt;/b&gt; in a coal mine in &lt;a href=&quot;/wiki/Heilongjiang&quot; title=&quot;Heilongjiang&quot;&gt;Heilongjiang&lt;/a&gt;, China, killed 108 miners.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Columbanus&quot; title=&quot;Columbanus&quot;&gt;Columbanus&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;615)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Joe_Darling&quot; title=&quot;Joe Darling&quot;&gt;Joe Darling&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1870)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Michael_Strahan&quot; title=&quot;Michael Strahan&quot;&gt;Michael Strahan&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1971)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_20&quot; title=&quot;November 20&quot;&gt;November 20&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_21&quot; title=&quot;November 21&quot;&gt;November 21&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_22&quot; title=&quot;November 22&quot;&gt;November 22&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211122000000/en</id>
		<title>On this day: November 22</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211122000000/en"/>
		<updated>2021-11-22T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_22&quot; title=&quot;November 22&quot;&gt;November 22&lt;/a&gt;&lt;/b&gt;: &lt;a href=&quot;/wiki/Calendar_of_saints&quot; title=&quot;Calendar of saints&quot;&gt;Feast day&lt;/a&gt; of &lt;b&gt;&lt;a href=&quot;/wiki/Saint_Cecilia&quot; title=&quot;Saint Cecilia&quot;&gt;Saint Cecilia&lt;/a&gt;&lt;/b&gt; (Christianity)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 122px;&quot;&gt;
&lt;a href=&quot;/wiki/File:General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_(1725).jpg&quot; class=&quot;image&quot; title=&quot;Blackbeard&quot;&gt;&lt;img alt=&quot;Blackbeard&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f7/General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_%281725%29.jpg/122px-General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_%281725%29.jpg&quot; decoding=&quot;async&quot; width=&quot;122&quot; height=&quot;161&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f7/General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_%281725%29.jpg/183px-General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_%281725%29.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f7/General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_%281725%29.jpg/244px-General_History_of_the_Pyrates_-_Blackbeard_the_Pirate_%281725%29.jpg 2x&quot; data-file-width=&quot;650&quot; data-file-height=&quot;860&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Blackbeard&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1635&quot; title=&quot;1635&quot;&gt;1635&lt;/a&gt; – &lt;a href=&quot;/wiki/Dutch_Formosa&quot; title=&quot;Dutch Formosa&quot;&gt;Dutch colonial forces on Taiwan&lt;/a&gt; launched &lt;b&gt;&lt;a href=&quot;/wiki/Dutch_pacification_campaign_on_Formosa&quot; title=&quot;Dutch pacification campaign on Formosa&quot;&gt;a three-month pacification campaign&lt;/a&gt;&lt;/b&gt; against &lt;a href=&quot;/wiki/Taiwanese_indigenous_peoples&quot; title=&quot;Taiwanese indigenous peoples&quot;&gt;the island's indigenous peoples&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1718&quot; title=&quot;1718&quot;&gt;1718&lt;/a&gt; – The pirate &lt;b&gt;&lt;a href=&quot;/wiki/Blackbeard&quot; title=&quot;Blackbeard&quot;&gt;Blackbeard&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; was killed in battle by a boarding party of British sailors off the coast of the &lt;a href=&quot;/wiki/Province_of_North_Carolina&quot; title=&quot;Province of North Carolina&quot;&gt;Province of North Carolina&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1908&quot; title=&quot;1908&quot;&gt;1908&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Congress_of_Manastir&quot; title=&quot;Congress of Manastir&quot;&gt;Congress of Manastir&lt;/a&gt;&lt;/b&gt; standardized the &lt;a href=&quot;/wiki/Albanian_alphabet&quot; title=&quot;Albanian alphabet&quot;&gt;Albanian alphabet&lt;/a&gt;, a date commemorated as Alphabet Day in Albania, Kosovo and North Macedonia.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1928&quot; title=&quot;1928&quot;&gt;1928&lt;/a&gt; – &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Bol%C3%A9ro&quot; title=&quot;Boléro&quot;&gt;Boléro&lt;/a&gt;&lt;/b&gt;&lt;/i&gt;, French composer &lt;a href=&quot;/wiki/Maurice_Ravel&quot; title=&quot;Maurice Ravel&quot;&gt;Maurice Ravel&lt;/a&gt;'s most famous musical composition, premiered at the &lt;a href=&quot;/wiki/Palais_Garnier&quot; title=&quot;Palais Garnier&quot;&gt;Paris Opéra&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt; – In Britain's worst mountaineering tragedy, the &lt;b&gt;&lt;a href=&quot;/wiki/Cairngorm_Plateau_disaster&quot; title=&quot;Cairngorm Plateau disaster&quot;&gt;Cairngorm Plateau disaster&lt;/a&gt;&lt;/b&gt;, five teenage students and one of their leaders were found dead from &lt;a href=&quot;/wiki/Hypothermia&quot; title=&quot;Hypothermia&quot;&gt;exposure&lt;/a&gt; in the &lt;a href=&quot;/wiki/Scottish_Highlands&quot; title=&quot;Scottish Highlands&quot;&gt;Scottish Highlands&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Joseph_Frederick_Wallet_DesBarres&quot; title=&quot;Joseph Frederick Wallet DesBarres&quot;&gt;Joseph Frederick Wallet DesBarres&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1721)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/John_Alsop&quot; title=&quot;John Alsop&quot;&gt;John Alsop&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1794)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mick_Shann&quot; title=&quot;Mick Shann&quot;&gt;Mick Shann&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1917)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_21&quot; title=&quot;November 21&quot;&gt;November 21&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_22&quot; title=&quot;November 22&quot;&gt;November 22&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_23&quot; title=&quot;November 23&quot;&gt;November 23&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211123000000/en</id>
		<title>On this day: November 23</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211123000000/en"/>
		<updated>2021-11-23T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_23&quot; title=&quot;November 23&quot;&gt;November 23&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Labor_Thanksgiving_Day&quot; title=&quot;Labor Thanksgiving Day&quot;&gt;Labor Thanksgiving Day&lt;/a&gt;&lt;/b&gt; in Japan
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 124px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Edwin-hubble.jpg&quot; class=&quot;image&quot; title=&quot;Edwin Hubble&quot;&gt;&lt;img alt=&quot;Edwin Hubble&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Edwin-hubble.jpg/124px-Edwin-hubble.jpg&quot; decoding=&quot;async&quot; width=&quot;124&quot; height=&quot;159&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Edwin-hubble.jpg/186px-Edwin-hubble.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/e/e5/Edwin-hubble.jpg 2x&quot; data-file-width=&quot;196&quot; data-file-height=&quot;251&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Edwin Hubble&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1733&quot; title=&quot;1733&quot;&gt;1733&lt;/a&gt; – African slaves in the &lt;a href=&quot;/wiki/Danish_West_Indies&quot; title=&quot;Danish West Indies&quot;&gt;Danish West Indies&lt;/a&gt; began &lt;b&gt;&lt;a href=&quot;/wiki/1733_slave_insurrection_on_St._John&quot; title=&quot;1733 slave insurrection on St. John&quot;&gt;an insurrection&lt;/a&gt;&lt;/b&gt; in one of the earliest and longest &lt;a href=&quot;/wiki/Slave_rebellion&quot; title=&quot;Slave rebellion&quot;&gt;slave revolts&lt;/a&gt; in the Americas.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1867&quot; title=&quot;1867&quot;&gt;1867&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Manchester_Martyrs&quot; title=&quot;Manchester Martyrs&quot;&gt;Manchester Martyrs&lt;/a&gt;&lt;/b&gt; were hanged in &lt;a href=&quot;/wiki/Manchester&quot; title=&quot;Manchester&quot;&gt;Manchester&lt;/a&gt;, England, for killing a police officer while helping two &lt;a href=&quot;/wiki/Irish_nationalism&quot; title=&quot;Irish nationalism&quot;&gt;Irish nationalists&lt;/a&gt; escape from police custody.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1924&quot; title=&quot;1924&quot;&gt;1924&lt;/a&gt; – &lt;i&gt;&lt;a href=&quot;/wiki/The_New_York_Times&quot; title=&quot;The New York Times&quot;&gt;The New York Times&lt;/a&gt;&lt;/i&gt; published evidence from &lt;b&gt;&lt;a href=&quot;/wiki/Edwin_Hubble&quot; title=&quot;Edwin Hubble&quot;&gt;Edwin Hubble&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; stating that the &lt;a href=&quot;/wiki/Andromeda_Galaxy&quot; title=&quot;Andromeda Galaxy&quot;&gt;Andromeda Nebula&lt;/a&gt;, previously believed to be part of the &lt;a href=&quot;/wiki/Milky_Way&quot; title=&quot;Milky Way&quot;&gt;Milky Way&lt;/a&gt;, is in fact another galaxy.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1976&quot; title=&quot;1976&quot;&gt;1976&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Jacques_Mayol&quot; title=&quot;Jacques Mayol&quot;&gt;Jacques Mayol&lt;/a&gt;&lt;/b&gt; became the first person to &lt;a href=&quot;/wiki/Freediving&quot; title=&quot;Freediving&quot;&gt;freedive&lt;/a&gt; to a depth of 100 metres (330&amp;#160;ft).&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2011&quot; title=&quot;2011&quot;&gt;2011&lt;/a&gt; – &lt;a href=&quot;/wiki/Arab_Spring&quot; title=&quot;Arab Spring&quot;&gt;Arab Spring&lt;/a&gt;: After &lt;a href=&quot;/wiki/Yemeni_Revolution&quot; title=&quot;Yemeni Revolution&quot;&gt;11 months of protests in Yemen&lt;/a&gt;, President &lt;b&gt;&lt;a href=&quot;/wiki/Ali_Abdullah_Saleh&quot; title=&quot;Ali Abdullah Saleh&quot;&gt;Ali Abdullah Saleh&lt;/a&gt;&lt;/b&gt; agreed to transfer power to Vice President &lt;b&gt;&lt;a href=&quot;/wiki/Abdrabbuh_Mansur_Hadi&quot; title=&quot;Abdrabbuh Mansur Hadi&quot;&gt;Abdrabbuh Mansur Hadi&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Beatriz_Galindo&quot; title=&quot;Beatriz Galindo&quot;&gt;Beatriz Galindo&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1535)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/El_Lissitzky&quot; title=&quot;El Lissitzky&quot;&gt;El Lissitzky&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1890)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mary_Whitehouse&quot; title=&quot;Mary Whitehouse&quot;&gt;Mary Whitehouse&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;2001)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_22&quot; title=&quot;November 22&quot;&gt;November 22&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_23&quot; title=&quot;November 23&quot;&gt;November 23&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_24&quot; title=&quot;November 24&quot;&gt;November 24&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211124000000/en</id>
		<title>On this day: November 24</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211124000000/en"/>
		<updated>2021-11-24T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_24&quot; title=&quot;November 24&quot;&gt;November 24&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 124px;&quot;&gt;
&lt;a href=&quot;/wiki/File:DBCooper.jpg&quot; class=&quot;image&quot; title=&quot;FBI composite drawing of D.&amp;#160;B. Cooper&quot;&gt;&lt;img alt=&quot;FBI composite drawing of D.&amp;#160;B. Cooper&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/DBCooper.jpg/124px-DBCooper.jpg&quot; decoding=&quot;async&quot; width=&quot;124&quot; height=&quot;157&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/DBCooper.jpg/186px-DBCooper.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/DBCooper.jpg/248px-DBCooper.jpg 2x&quot; data-file-width=&quot;309&quot; data-file-height=&quot;392&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;FBI composite drawing of D.&amp;#160;B. Cooper&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1227&quot; title=&quot;1227&quot;&gt;1227&lt;/a&gt; – &lt;a href=&quot;/wiki/Leszek_the_White&quot; title=&quot;Leszek the White&quot;&gt;Leszek the White&lt;/a&gt;, High Duke of Poland, &lt;b&gt;&lt;a href=&quot;/wiki/G%C4%85sawa_massacre&quot; title=&quot;Gąsawa massacre&quot;&gt;was assassinated&lt;/a&gt;&lt;/b&gt; during a meeting of &lt;a href=&quot;/wiki/Piast_dynasty&quot; title=&quot;Piast dynasty&quot;&gt;Piast&lt;/a&gt; dukes.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1859&quot; title=&quot;1859&quot;&gt;1859&lt;/a&gt; – British naturalist &lt;a href=&quot;/wiki/Charles_Darwin&quot; title=&quot;Charles Darwin&quot;&gt;Charles Darwin&lt;/a&gt;'s &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/On_the_Origin_of_Species&quot; title=&quot;On the Origin of Species&quot;&gt;On the Origin of Species&lt;/a&gt;&lt;/b&gt;&lt;/i&gt; was first published, and sold out its initial print run on the first day.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – &lt;a href=&quot;/wiki/The_Holocaust&quot; title=&quot;The Holocaust&quot;&gt;The Holocaust&lt;/a&gt;: The &lt;b&gt;&lt;a href=&quot;/wiki/Theresienstadt_Ghetto&quot; title=&quot;Theresienstadt Ghetto&quot;&gt;Theresienstadt Ghetto&lt;/a&gt;&lt;/b&gt; was founded as a waystation to Nazi &lt;a href=&quot;/wiki/Extermination_camp&quot; title=&quot;Extermination camp&quot;&gt;extermination camps&lt;/a&gt; and a &quot;retirement settlement&quot; for elderly and prominent Jews to mislead their communities about the &lt;a href=&quot;/wiki/Final_Solution&quot; title=&quot;Final Solution&quot;&gt;Final Solution&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt; – After collecting a ransom payout of $200,000, &lt;b&gt;&lt;a href=&quot;/wiki/D._B._Cooper&quot; title=&quot;D. B. Cooper&quot;&gt;D.&amp;#160;B. Cooper&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(depicted)&lt;/i&gt; parachuted out of the rear stairway of the airplane he had hijacked over the &lt;a href=&quot;/wiki/Pacific_Northwest&quot; title=&quot;Pacific Northwest&quot;&gt;Pacific Northwest&lt;/a&gt; and disappeared.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2015&quot; title=&quot;2015&quot;&gt;2015&lt;/a&gt; – A Turkish fighter jet &lt;b&gt;&lt;a href=&quot;/wiki/2015_Russian_Sukhoi_Su-24_shootdown&quot; title=&quot;2015 Russian Sukhoi Su-24 shootdown&quot;&gt;shot down&lt;/a&gt;&lt;/b&gt; a Russian &lt;a href=&quot;/wiki/Sukhoi_Su-24&quot; title=&quot;Sukhoi Su-24&quot;&gt;Sukhoi &lt;span class=&quot;nowrap&quot;&gt;Su-24&lt;/span&gt;&lt;/a&gt; after the latter allegedly strayed into Turkish airspace and ignored warnings to change course.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mingyi_Nyo&quot; title=&quot;Mingyi Nyo&quot;&gt;Mingyi Nyo&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1530)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Zachary_Taylor&quot; title=&quot;Zachary Taylor&quot;&gt;Zachary Taylor&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1784)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Arundhati_Roy&quot; title=&quot;Arundhati Roy&quot;&gt;Arundhati Roy&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1961)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_23&quot; title=&quot;November 23&quot;&gt;November 23&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_24&quot; title=&quot;November 24&quot;&gt;November 24&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_25&quot; title=&quot;November 25&quot;&gt;November 25&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211125000000/en</id>
		<title>On this day: November 25</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211125000000/en"/>
		<updated>2021-11-25T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_25&quot; title=&quot;November 25&quot;&gt;November 25&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Evacuation_Day_(New_York)&quot; title=&quot;Evacuation Day (New York)&quot;&gt;Evacuation Day&lt;/a&gt;&lt;/b&gt; in New York City (&lt;a href=&quot;/wiki/1783&quot; title=&quot;1783&quot;&gt;1783&lt;/a&gt;); &lt;b&gt;&lt;a href=&quot;/wiki/Thanksgiving_(United_States)&quot; title=&quot;Thanksgiving (United States)&quot;&gt;Thanksgiving&lt;/a&gt;&lt;/b&gt; in the United States (2021)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 121px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Ferrier_in_Suriname_1975_(cropped).jpg&quot; class=&quot;image&quot; title=&quot;Johan Ferrier in 1975&quot;&gt;&lt;img alt=&quot;Johan Ferrier in 1975&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ferrier_in_Suriname_1975_%28cropped%29.jpg/121px-Ferrier_in_Suriname_1975_%28cropped%29.jpg&quot; decoding=&quot;async&quot; width=&quot;121&quot; height=&quot;161&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ferrier_in_Suriname_1975_%28cropped%29.jpg/182px-Ferrier_in_Suriname_1975_%28cropped%29.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ferrier_in_Suriname_1975_%28cropped%29.jpg/242px-Ferrier_in_Suriname_1975_%28cropped%29.jpg 2x&quot; data-file-width=&quot;799&quot; data-file-height=&quot;1066&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Johan Ferrier in 1975&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1510&quot; title=&quot;1510&quot;&gt;1510&lt;/a&gt; – &lt;a href=&quot;/wiki/Afonso_de_Albuquerque&quot; title=&quot;Afonso de Albuquerque&quot;&gt;Afonso de Albuquerque&lt;/a&gt;, the governor of &lt;a href=&quot;/wiki/Portuguese_India&quot; title=&quot;Portuguese India&quot;&gt;Portuguese India&lt;/a&gt;, led an armada to &lt;b&gt;&lt;a href=&quot;/wiki/Portuguese_conquest_of_Goa&quot; title=&quot;Portuguese conquest of Goa&quot;&gt;conquer Goa&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1678&quot; title=&quot;1678&quot;&gt;1678&lt;/a&gt; – &lt;a href=&quot;/wiki/Trunajaya_rebellion&quot; title=&quot;Trunajaya rebellion&quot;&gt;Trunajaya rebellion&lt;/a&gt;: After a series of difficult marches, allied &lt;a href=&quot;/wiki/Mataram_Sultanate&quot; title=&quot;Mataram Sultanate&quot;&gt;Mataram&lt;/a&gt; and &lt;a href=&quot;/wiki/Dutch_East_India_Company&quot; title=&quot;Dutch East India Company&quot;&gt;Dutch&lt;/a&gt; troops &lt;b&gt;&lt;a href=&quot;/wiki/1678_Kediri_campaign&quot; title=&quot;1678 Kediri campaign&quot;&gt;successfully assaulted&lt;/a&gt;&lt;/b&gt; the rebel stronghold of &lt;a href=&quot;/wiki/Kediri_(city)&quot; title=&quot;Kediri (city)&quot;&gt;Kediri&lt;/a&gt; in eastern &lt;a href=&quot;/wiki/Java&quot; title=&quot;Java&quot;&gt;Java&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1936&quot; title=&quot;1936&quot;&gt;1936&lt;/a&gt; – Nazi Germany and the Empire of Japan signed the &lt;b&gt;&lt;a href=&quot;/wiki/Anti-Comintern_Pact&quot; title=&quot;Anti-Comintern Pact&quot;&gt;Anti-Comintern Pact&lt;/a&gt;&lt;/b&gt;, agreeing that, if the Soviet Union attacked one of them, they would consult each other on what measures to take to &quot;safeguard their common interests&quot;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1975&quot; title=&quot;1975&quot;&gt;1975&lt;/a&gt; – Upon Suriname's independence from the Netherlands, &lt;b&gt;&lt;a href=&quot;/wiki/Johan_Ferrier&quot; title=&quot;Johan Ferrier&quot;&gt;Johan Ferrier&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; became its &lt;a href=&quot;/wiki/President_of_Suriname&quot; title=&quot;President of Suriname&quot;&gt;first president&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Johann_Georg_Pisendel&quot; title=&quot;Johann Georg Pisendel&quot;&gt;Johann Georg Pisendel&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1755)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Maurice_Denis&quot; title=&quot;Maurice Denis&quot;&gt;Maurice Denis&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1870)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/John_F._Kennedy_Jr.&quot; title=&quot;John F. Kennedy Jr.&quot;&gt;John&amp;#160;F. Kennedy&amp;#160;Jr.&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1960)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_24&quot; title=&quot;November 24&quot;&gt;November 24&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_25&quot; title=&quot;November 25&quot;&gt;November 25&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_26&quot; title=&quot;November 26&quot;&gt;November 26&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
</feed>