<?xml version="1.0"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
	<id>https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom</id>
	<title>Wikipedia &quot;On this day...&quot; feed</title>
	<link rel="self" type="application/atom+xml" href="https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom"/>
	<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Main_Page"/>
	<updated>2021-12-05T19:41:03Z</updated>
	<subtitle>Historical events on this day</subtitle>
	<generator>MediaWiki 1.38.0-wmf.9</generator>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211126000000/en</id>
		<title>On this day: November 26</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211126000000/en"/>
		<updated>2021-11-26T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_26&quot; title=&quot;November 26&quot;&gt;November 26&lt;/a&gt;&lt;/b&gt;: &lt;a href=&quot;/wiki/Calendar_of_saints&quot; title=&quot;Calendar of saints&quot;&gt;Feast day&lt;/a&gt; of &lt;b&gt;&lt;a href=&quot;/wiki/Sylvester_Gozzolini&quot; title=&quot;Sylvester Gozzolini&quot;&gt;Saint Sylvester Gozzolini&lt;/a&gt;&lt;/b&gt; (&lt;a href=&quot;/wiki/Catholic_Church&quot; title=&quot;Catholic Church&quot;&gt;Catholicism&lt;/a&gt;); &lt;b&gt;&lt;a href=&quot;/wiki/Constitution_Day_(India)&quot; title=&quot;Constitution Day (India)&quot;&gt;Constitution Day&lt;/a&gt;&lt;/b&gt; in India (&lt;a href=&quot;/wiki/1949&quot; title=&quot;1949&quot;&gt;1949&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 114px;&quot;&gt;
&lt;a href=&quot;/wiki/File:NDU-Goldkuppel.jpg&quot; class=&quot;image&quot; title=&quot;Main Building of the University of Notre Dame&quot;&gt;&lt;img alt=&quot;Main Building of the University of Notre Dame&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/9/92/NDU-Goldkuppel.jpg/114px-NDU-Goldkuppel.jpg&quot; decoding=&quot;async&quot; width=&quot;114&quot; height=&quot;171&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/9/92/NDU-Goldkuppel.jpg/171px-NDU-Goldkuppel.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/92/NDU-Goldkuppel.jpg/228px-NDU-Goldkuppel.jpg 2x&quot; data-file-width=&quot;1200&quot; data-file-height=&quot;1800&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;&lt;a href=&quot;/wiki/Main_Building_(University_of_Notre_Dame)&quot; title=&quot;Main Building (University of Notre Dame)&quot;&gt;Main Building&lt;/a&gt; of the University of Notre Dame&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1842&quot; title=&quot;1842&quot;&gt;1842&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/University_of_Notre_Dame&quot; title=&quot;University of Notre Dame&quot;&gt;University of Notre Dame&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(main building pictured)&lt;/i&gt; was founded by &lt;a href=&quot;/wiki/Edward_Sorin&quot; title=&quot;Edward Sorin&quot;&gt;Edward Sorin&lt;/a&gt; of the &lt;a href=&quot;/wiki/Congregation_of_Holy_Cross&quot; title=&quot;Congregation of Holy Cross&quot;&gt;Congregation of Holy Cross&lt;/a&gt; as an all-male institution in the U.S. state of &lt;a href=&quot;/wiki/Indiana&quot; title=&quot;Indiana&quot;&gt;Indiana&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1852&quot; title=&quot;1852&quot;&gt;1852&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/1852_Banda_Sea_earthquake&quot; title=&quot;1852 Banda Sea earthquake&quot;&gt;A massive earthquake&lt;/a&gt;&lt;/b&gt; struck the &lt;a href=&quot;/wiki/Dutch_East_Indies&quot; title=&quot;Dutch East Indies&quot;&gt;Dutch East Indies&lt;/a&gt;, creating a &lt;a href=&quot;/wiki/Tsunami&quot; title=&quot;Tsunami&quot;&gt;tsunami&lt;/a&gt; that caused major damage, washing away many villages, ships and residents.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1983&quot; title=&quot;1983&quot;&gt;1983&lt;/a&gt; – Six robbers broke into a &lt;a href=&quot;/wiki/Brink%27s&quot; title=&quot;Brink&amp;#39;s&quot;&gt;Brink's-Mat&lt;/a&gt; warehouse at &lt;a href=&quot;/wiki/Heathrow_Airport&quot; title=&quot;Heathrow Airport&quot;&gt;Heathrow Airport&lt;/a&gt; in London and &lt;b&gt;&lt;a href=&quot;/wiki/Brink%27s-Mat_robbery&quot; title=&quot;Brink&amp;#39;s-Mat robbery&quot;&gt;stole £26&amp;#160;million in gold, diamonds and cash&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2011&quot; title=&quot;2011&quot;&gt;2011&lt;/a&gt; – U.S.-led &lt;a href=&quot;/wiki/NATO&quot; title=&quot;NATO&quot;&gt;NATO&lt;/a&gt; forces &lt;b&gt;&lt;a href=&quot;/wiki/2011_NATO_attack_in_Pakistan&quot; title=&quot;2011 NATO attack in Pakistan&quot;&gt;engaged&lt;/a&gt;&lt;/b&gt; &lt;a href=&quot;/wiki/Pakistan_Army&quot; title=&quot;Pakistan Army&quot;&gt;Pakistani security forces&lt;/a&gt; at two Pakistani military checkposts along the &lt;a href=&quot;/wiki/Durand_Line&quot; title=&quot;Durand Line&quot;&gt;Afghanistan–Pakistan border&lt;/a&gt; in a &lt;a href=&quot;/wiki/Friendly_fire&quot; title=&quot;Friendly fire&quot;&gt;friendly fire&lt;/a&gt; incident.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Ralph_Agas&quot; title=&quot;Ralph Agas&quot;&gt;Ralph Agas&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1621)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Helen_C._White&quot; title=&quot;Helen C. White&quot;&gt;Helen C. White&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1896)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Adolfo_P%C3%A9rez_Esquivel&quot; title=&quot;Adolfo Pérez Esquivel&quot;&gt;Adolfo Pérez Esquivel&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1931)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_25&quot; title=&quot;November 25&quot;&gt;November 25&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_26&quot; title=&quot;November 26&quot;&gt;November 26&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_27&quot; title=&quot;November 27&quot;&gt;November 27&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211127000000/en</id>
		<title>On this day: November 27</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211127000000/en"/>
		<updated>2021-11-27T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_27&quot; title=&quot;November 27&quot;&gt;November 27&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 117px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Osirisplanet.jpg&quot; class=&quot;image&quot; title=&quot;NASA drawing of the extrasolar planet Osiris&quot;&gt;&lt;img alt=&quot;NASA drawing of the extrasolar planet Osiris&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Osirisplanet.jpg/117px-Osirisplanet.jpg&quot; decoding=&quot;async&quot; width=&quot;117&quot; height=&quot;167&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Osirisplanet.jpg/176px-Osirisplanet.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Osirisplanet.jpg/234px-Osirisplanet.jpg 2x&quot; data-file-width=&quot;1305&quot; data-file-height=&quot;1865&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;NASA drawing of the extrasolar planet Osiris&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1095&quot; title=&quot;1095&quot;&gt;1095&lt;/a&gt; – At the &lt;b&gt;&lt;a href=&quot;/wiki/Council_of_Clermont&quot; title=&quot;Council of Clermont&quot;&gt;Council of Clermont&lt;/a&gt;&lt;/b&gt;, &lt;a href=&quot;/wiki/Pope_Urban_II&quot; title=&quot;Pope Urban II&quot;&gt;Pope Urban&amp;#160;II&lt;/a&gt; called for the &lt;a href=&quot;/wiki/First_Crusade&quot; title=&quot;First Crusade&quot;&gt;First Crusade&lt;/a&gt;, declaring &lt;a href=&quot;/wiki/Religious_war&quot; title=&quot;Religious war&quot;&gt;holy war&lt;/a&gt; against the &lt;a href=&quot;/wiki/Muslims&quot; title=&quot;Muslims&quot;&gt;Muslims&lt;/a&gt; who had occupied the &lt;a href=&quot;/wiki/Holy_Land&quot; title=&quot;Holy Land&quot;&gt;Holy Land&lt;/a&gt; and were attacking the &lt;a href=&quot;/wiki/Byzantine_Empire&quot; title=&quot;Byzantine Empire&quot;&gt;Eastern Roman Empire&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1703&quot; title=&quot;1703&quot;&gt;1703&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Great_storm_of_1703&quot; title=&quot;Great storm of 1703&quot;&gt;great storm of 1703&lt;/a&gt;&lt;/b&gt;, one of the most severe storms to strike southern &lt;a href=&quot;/wiki/Great_Britain&quot; title=&quot;Great Britain&quot;&gt;Great Britain&lt;/a&gt;, destroyed the first &lt;a href=&quot;/wiki/Eddystone_Lighthouse&quot; title=&quot;Eddystone Lighthouse&quot;&gt;Eddystone Lighthouse&lt;/a&gt; off &lt;a href=&quot;/wiki/Plymouth&quot; title=&quot;Plymouth&quot;&gt;Plymouth&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1945&quot; title=&quot;1945&quot;&gt;1945&lt;/a&gt; – A consortium of twenty-two U.S. charities founded &lt;b&gt;&lt;a href=&quot;/wiki/Care_International&quot; title=&quot;Care International&quot;&gt;CARE&lt;/a&gt;&lt;/b&gt; with the purpose of delivering food aid to Europe in the &lt;a href=&quot;/wiki/Aftermath_of_World_War_II&quot; title=&quot;Aftermath of World War II&quot;&gt;aftermath of World War&amp;#160;II&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2001&quot; title=&quot;2001&quot;&gt;2001&lt;/a&gt; – The &lt;a href=&quot;/wiki/Hubble_Space_Telescope&quot; title=&quot;Hubble Space Telescope&quot;&gt;Hubble Space Telescope&lt;/a&gt; detected &lt;a href=&quot;/wiki/Sodium&quot; title=&quot;Sodium&quot;&gt;sodium&lt;/a&gt; in the atmosphere of the extrasolar planet &lt;b&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a href=&quot;/wiki/HD_209458_b&quot; title=&quot;HD 209458 b&quot;&gt;HD 209458 b&lt;/a&gt;&lt;/span&gt;&lt;/b&gt; &lt;i&gt;(artist's impression pictured)&lt;/i&gt;, the first planetary atmosphere &lt;a href=&quot;/wiki/Exoplanet&quot; title=&quot;Exoplanet&quot;&gt;outside our solar system&lt;/a&gt; to be measured.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Increase_Sumner&quot; title=&quot;Increase Sumner&quot;&gt;Increase Sumner&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1746)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Jean_Albert_Gaudry&quot; title=&quot;Jean Albert Gaudry&quot;&gt;Jean Albert Gaudry&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1908)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Gary_Speed&quot; title=&quot;Gary Speed&quot;&gt;Gary Speed&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;2011)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_26&quot; title=&quot;November 26&quot;&gt;November 26&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_27&quot; title=&quot;November 27&quot;&gt;November 27&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_28&quot; title=&quot;November 28&quot;&gt;November 28&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211128000000/en</id>
		<title>On this day: November 28</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211128000000/en"/>
		<updated>2021-11-28T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_28&quot; title=&quot;November 28&quot;&gt;November 28&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Bukovina_Day&quot; title=&quot;Bukovina Day&quot;&gt;Bukovina Day&lt;/a&gt;&lt;/b&gt; in Romania (&lt;a href=&quot;/wiki/1918&quot; title=&quot;1918&quot;&gt;1918&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 155px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Tehran_Conference,_1943.jpg&quot; class=&quot;image&quot; title=&quot;Stalin, Roosevelt, and Churchill in Tehran&quot;&gt;&lt;img alt=&quot;Stalin, Roosevelt, and Churchill in Tehran&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tehran_Conference%2C_1943.jpg/155px-Tehran_Conference%2C_1943.jpg&quot; decoding=&quot;async&quot; width=&quot;155&quot; height=&quot;126&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tehran_Conference%2C_1943.jpg/233px-Tehran_Conference%2C_1943.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tehran_Conference%2C_1943.jpg/310px-Tehran_Conference%2C_1943.jpg 2x&quot; data-file-width=&quot;700&quot; data-file-height=&quot;569&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Stalin, Roosevelt, and Churchill in Tehran&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/936&quot; title=&quot;936&quot;&gt;936&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Shi_Jingtang&quot; title=&quot;Shi Jingtang&quot;&gt;Shi Jingtang&lt;/a&gt;&lt;/b&gt; was enthroned as the first emperor of the &lt;a href=&quot;/wiki/Later_Jin_(Five_Dynasties)&quot; title=&quot;Later Jin (Five Dynasties)&quot;&gt;Later Jin&lt;/a&gt; by &lt;a href=&quot;/wiki/Emperor_Taizong_of_Liao&quot; title=&quot;Emperor Taizong of Liao&quot;&gt;Emperor Taizong of Liao&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1660&quot; title=&quot;1660&quot;&gt;1660&lt;/a&gt; – At London's &lt;a href=&quot;/wiki/Gresham_College&quot; title=&quot;Gresham College&quot;&gt;Gresham College&lt;/a&gt;, &lt;a href=&quot;/wiki/Robert_Boyle&quot; title=&quot;Robert Boyle&quot;&gt;Robert Boyle&lt;/a&gt;, &lt;a href=&quot;/wiki/John_Wilkins&quot; title=&quot;John Wilkins&quot;&gt;John Wilkins&lt;/a&gt;, &lt;a href=&quot;/wiki/Christopher_Wren&quot; title=&quot;Christopher Wren&quot;&gt;Christopher Wren&lt;/a&gt; and other leading scientists founded a &lt;a href=&quot;/wiki/Learned_society&quot; title=&quot;Learned society&quot;&gt;learned society&lt;/a&gt; now known as the &lt;b&gt;&lt;a href=&quot;/wiki/Royal_Society&quot; title=&quot;Royal Society&quot;&gt;Royal Society&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1943&quot; title=&quot;1943&quot;&gt;1943&lt;/a&gt; – &lt;a href=&quot;/wiki/World_War_II&quot; title=&quot;World War II&quot;&gt;World War&amp;#160;II&lt;/a&gt;: U.S. president &lt;a href=&quot;/wiki/Franklin_D._Roosevelt&quot; title=&quot;Franklin D. Roosevelt&quot;&gt;Franklin D. Roosevelt&lt;/a&gt;, British prime minister &lt;a href=&quot;/wiki/Winston_Churchill&quot; title=&quot;Winston Churchill&quot;&gt;Winston Churchill&lt;/a&gt;, and Soviet premier &lt;a href=&quot;/wiki/Joseph_Stalin&quot; title=&quot;Joseph Stalin&quot;&gt;Joseph Stalin&lt;/a&gt; &lt;i&gt;(all three pictured)&lt;/i&gt; met at the &lt;b&gt;&lt;a href=&quot;/wiki/Tehran_Conference&quot; title=&quot;Tehran Conference&quot;&gt;Tehran Conference&lt;/a&gt;&lt;/b&gt; to discuss war strategy against the &lt;a href=&quot;/wiki/Axis_powers&quot; title=&quot;Axis powers&quot;&gt;Axis powers&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1987&quot; title=&quot;1987&quot;&gt;1987&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/South_African_Airways_Flight_295&quot; title=&quot;South African Airways Flight 295&quot;&gt;South African Airways Flight&amp;#160;295&lt;/a&gt;&lt;/b&gt; suffered a catastrophic in-flight fire and crashed into the Indian Ocean east of Mauritius, killing all 159 on board.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Abraham_Brueghel&quot; title=&quot;Abraham Brueghel&quot;&gt;Abraham Brueghel&lt;/a&gt;&lt;/b&gt;  (bapt.&amp;#160;1631)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Gregorio_Perfecto&quot; title=&quot;Gregorio Perfecto&quot;&gt;Gregorio Perfecto&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1891)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/%CA%BBAbdu%27l-Bah%C3%A1&quot; title=&quot;ʻAbdu&amp;#39;l-Bahá&quot;&gt;ʻAbdu'l-Bahá&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1921)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_27&quot; title=&quot;November 27&quot;&gt;November 27&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_28&quot; title=&quot;November 28&quot;&gt;November 28&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_29&quot; title=&quot;November 29&quot;&gt;November 29&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211129000000/en</id>
		<title>On this day: November 29</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211129000000/en"/>
		<updated>2021-11-29T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_29&quot; title=&quot;November 29&quot;&gt;November 29&lt;/a&gt;&lt;/b&gt;: First day of &lt;b&gt;&lt;a href=&quot;/wiki/Hanukkah&quot; title=&quot;Hanukkah&quot;&gt;Hanukkah&lt;/a&gt;&lt;/b&gt; (Judaism, 2021); &lt;b&gt;&lt;a href=&quot;/wiki/Liberation_Day_(Albania)&quot; title=&quot;Liberation Day (Albania)&quot;&gt;Liberation Day&lt;/a&gt;&lt;/b&gt; in Albania (&lt;a href=&quot;/wiki/1944&quot; title=&quot;1944&quot;&gt;1944&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 172px;&quot;&gt;
&lt;a href=&quot;/wiki/File:The_Diet.jpg&quot; class=&quot;image&quot; title=&quot;Joint session of the National Diet of Japan in 2002&quot;&gt;&lt;img alt=&quot;Joint session of the National Diet of Japan in 2002&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/c/c5/The_Diet.jpg/172px-The_Diet.jpg&quot; decoding=&quot;async&quot; width=&quot;172&quot; height=&quot;114&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/c/c5/The_Diet.jpg/258px-The_Diet.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c5/The_Diet.jpg/344px-The_Diet.jpg 2x&quot; data-file-width=&quot;400&quot; data-file-height=&quot;266&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Joint session of the National Diet of Japan in 2002&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/903&quot; title=&quot;903&quot;&gt;903&lt;/a&gt; – The &lt;a href=&quot;/wiki/Abbasid_Caliphate&quot; title=&quot;Abbasid Caliphate&quot;&gt;Abbasid Caliphate&lt;/a&gt; captured the &lt;a href=&quot;/wiki/Qarmatians&quot; title=&quot;Qarmatians&quot;&gt;Qarmatian&lt;/a&gt; leadership in the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Hama&quot; title=&quot;Battle of Hama&quot;&gt;Battle of Hama&lt;/a&gt;&lt;/b&gt; in Syria, opening the way for the reconquest of &lt;a href=&quot;/wiki/Tulunids&quot; title=&quot;Tulunids&quot;&gt;Tulunid&lt;/a&gt; Egypt.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1776&quot; title=&quot;1776&quot;&gt;1776&lt;/a&gt; – &lt;a href=&quot;/wiki/American_Revolutionary_War&quot; title=&quot;American Revolutionary War&quot;&gt;American Revolutionary War&lt;/a&gt;: British reinforcements brought an end to the &lt;a href=&quot;/wiki/Patriot_(American_Revolution)&quot; title=&quot;Patriot (American Revolution)&quot;&gt;Patriot&lt;/a&gt; attempt to &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Fort_Cumberland_(1776)&quot; title=&quot;Battle of Fort Cumberland (1776)&quot;&gt;capture&lt;/a&gt;&lt;/b&gt; &lt;a href=&quot;/wiki/Fort_Beaus%C3%A9jour&quot; title=&quot;Fort Beauséjour&quot;&gt;Fort Cumberland&lt;/a&gt; in &lt;a href=&quot;/wiki/Nova_Scotia&quot; title=&quot;Nova Scotia&quot;&gt;Nova Scotia&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1890&quot; title=&quot;1890&quot;&gt;1890&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/National_Diet&quot; title=&quot;National Diet&quot;&gt;National Diet&lt;/a&gt;&lt;/b&gt; of Japan &lt;i&gt;(pictured in session)&lt;/i&gt;, a &lt;a href=&quot;/wiki/Bicameralism&quot; title=&quot;Bicameralism&quot;&gt;bicameral legislature&lt;/a&gt; modelled after both the German &lt;a href=&quot;/wiki/Reichstag_(German_Empire)&quot; title=&quot;Reichstag (German Empire)&quot;&gt;Reichstag&lt;/a&gt; and the British &lt;a href=&quot;/wiki/Westminster_system&quot; title=&quot;Westminster system&quot;&gt;Westminster system&lt;/a&gt;, first met in Tokyo.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2007&quot; title=&quot;2007&quot;&gt;2007&lt;/a&gt; – During their trial for the 2003 &lt;a href=&quot;/wiki/Oakwood_mutiny&quot; title=&quot;Oakwood mutiny&quot;&gt;Oakwood mutiny&lt;/a&gt;, Philippine soldiers led by Senator &lt;a href=&quot;/wiki/Antonio_Trillanes&quot; title=&quot;Antonio Trillanes&quot;&gt;Antonio Trillanes&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Manila_Peninsula_siege&quot; title=&quot;Manila Peninsula siege&quot;&gt;mutinied and seized&lt;/a&gt;&lt;/b&gt; a conference room in &lt;a href=&quot;/wiki/The_Peninsula_Manila&quot; title=&quot;The Peninsula Manila&quot;&gt;The Peninsula Manila&lt;/a&gt; hotel in &lt;a href=&quot;/wiki/Makati&quot; title=&quot;Makati&quot;&gt;Makati&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Claudio_Monteverdi&quot; title=&quot;Claudio Monteverdi&quot;&gt;Claudio Monteverdi&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1643)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mary_Somerville&quot; title=&quot;Mary Somerville&quot;&gt;Mary Somerville&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1872)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Lalit_Modi&quot; title=&quot;Lalit Modi&quot;&gt;Lalit Modi&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1963)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_28&quot; title=&quot;November 28&quot;&gt;November 28&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_29&quot; title=&quot;November 29&quot;&gt;November 29&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/November_30&quot; title=&quot;November 30&quot;&gt;November 30&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211130000000/en</id>
		<title>On this day: November 30</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211130000000/en"/>
		<updated>2021-11-30T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_30&quot; title=&quot;November 30&quot;&gt;November 30&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Day_of_Remembrance_for_All_Victims_of_Chemical_Warfare&quot; title=&quot;Day of Remembrance for All Victims of Chemical Warfare&quot;&gt;Day of Remembrance for All Victims of Chemical Warfare&lt;/a&gt;&lt;/b&gt;; &lt;b&gt;&lt;a href=&quot;/wiki/Saint_Andrew%27s_Day&quot; title=&quot;Saint Andrew&amp;#39;s Day&quot;&gt;Saint Andrew's Day&lt;/a&gt;&lt;/b&gt; (Christianity)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 162px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Model_of_a_Turing_machine.jpg&quot; class=&quot;image&quot; title=&quot;Model of a Turing machine&quot;&gt;&lt;img alt=&quot;Model of a Turing machine&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Model_of_a_Turing_machine.jpg/162px-Model_of_a_Turing_machine.jpg&quot; decoding=&quot;async&quot; width=&quot;162&quot; height=&quot;122&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Model_of_a_Turing_machine.jpg/243px-Model_of_a_Turing_machine.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Model_of_a_Turing_machine.jpg/324px-Model_of_a_Turing_machine.jpg 2x&quot; data-file-width=&quot;3264&quot; data-file-height=&quot;2448&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Model of a Turing machine&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1853&quot; title=&quot;1853&quot;&gt;1853&lt;/a&gt; – &lt;a href=&quot;/wiki/Crimean_War&quot; title=&quot;Crimean War&quot;&gt;Crimean War&lt;/a&gt;: Russian warships led by &lt;a href=&quot;/wiki/Pavel_Nakhimov&quot; title=&quot;Pavel Nakhimov&quot;&gt;Pavel Nakhimov&lt;/a&gt; destroyed an &lt;a href=&quot;/wiki/Ottoman_Empire&quot; title=&quot;Ottoman Empire&quot;&gt;Ottoman&lt;/a&gt; fleet of &lt;a href=&quot;/wiki/Frigate&quot; title=&quot;Frigate&quot;&gt;frigates&lt;/a&gt; at the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Sinop&quot; title=&quot;Battle of Sinop&quot;&gt;Battle of Sinop&lt;/a&gt;&lt;/b&gt;, prompting France and Britain to enter the war.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1936&quot; title=&quot;1936&quot;&gt;1936&lt;/a&gt; – English mathematician &lt;b&gt;&lt;a href=&quot;/wiki/Alan_Turing&quot; title=&quot;Alan Turing&quot;&gt;Alan Turing&lt;/a&gt;&lt;/b&gt; published details of the &lt;a href=&quot;/wiki/Turing_machine&quot; title=&quot;Turing machine&quot;&gt;Turing machine&lt;/a&gt; &lt;i&gt;(model pictured)&lt;/i&gt;, a basic abstract symbol-manipulating hypothetical device that can simulate the logic of any computer &lt;a href=&quot;/wiki/Algorithm&quot; title=&quot;Algorithm&quot;&gt;algorithm&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1954&quot; title=&quot;1954&quot;&gt;1954&lt;/a&gt; – The first verified case of a human being injured by an extraterrestrial object took place in &lt;a href=&quot;/wiki/Sylacauga,_Alabama&quot; title=&quot;Sylacauga, Alabama&quot;&gt;Sylacauga, Alabama&lt;/a&gt;, when &lt;b&gt;&lt;a href=&quot;/wiki/Sylacauga_(meteorite)&quot; title=&quot;Sylacauga (meteorite)&quot;&gt;a meteorite crashed through a roof&lt;/a&gt;&lt;/b&gt; and hit a sleeping woman.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2005&quot; title=&quot;2005&quot;&gt;2005&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/John_Sentamu&quot; title=&quot;John Sentamu&quot;&gt;John Sentamu&lt;/a&gt;&lt;/b&gt; was enthroned as &lt;a href=&quot;/wiki/Archbishop_of_York&quot; title=&quot;Archbishop of York&quot;&gt;Archbishop of York&lt;/a&gt;, becoming the first black person to serve as an archbishop in the &lt;a href=&quot;/wiki/Church_of_England&quot; title=&quot;Church of England&quot;&gt;Church of England&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Alexander_Berry&quot; title=&quot;Alexander Berry&quot;&gt;Alexander Berry&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1781)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Frederick_Temple&quot; title=&quot;Frederick Temple&quot;&gt;Frederick Temple&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1821)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Mahmud_Hasan_Deobandi&quot; title=&quot;Mahmud Hasan Deobandi&quot;&gt;Mahmud Hasan Deobandi&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1920)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_29&quot; title=&quot;November 29&quot;&gt;November 29&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/November_30&quot; title=&quot;November 30&quot;&gt;November 30&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_1&quot; title=&quot;December 1&quot;&gt;December 1&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/November&quot; title=&quot;Wikipedia:Selected anniversaries/November&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211201000000/en</id>
		<title>On this day: December 1</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211201000000/en"/>
		<updated>2021-12-01T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_1&quot; title=&quot;December 1&quot;&gt;December 1&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/World_AIDS_Day&quot; title=&quot;World AIDS Day&quot;&gt;World AIDS Day&lt;/a&gt;&lt;/b&gt;; &lt;b&gt;&lt;a href=&quot;/wiki/Great_Union_Day&quot; title=&quot;Great Union Day&quot;&gt;Great Union Day&lt;/a&gt;&lt;/b&gt; in Romania (&lt;a href=&quot;/wiki/1918&quot; title=&quot;1918&quot;&gt;1918&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 126px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg&quot; class=&quot;image&quot; title=&quot;Francis Walsingham&quot;&gt;&lt;img alt=&quot;Francis Walsingham&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg/126px-Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg&quot; decoding=&quot;async&quot; width=&quot;126&quot; height=&quot;154&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg/189px-Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg/252px-Sir_Francis_Walsingham_by_John_De_Critz_the_Elder.jpg 2x&quot; data-file-width=&quot;2400&quot; data-file-height=&quot;2940&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Francis Walsingham&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1577&quot; title=&quot;1577&quot;&gt;1577&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Francis_Walsingham&quot; title=&quot;Francis Walsingham&quot;&gt;Francis Walsingham&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt;, &lt;a href=&quot;/wiki/Elizabeth_I&quot; title=&quot;Elizabeth I&quot;&gt;Elizabeth&amp;#160;I of England&lt;/a&gt;'s &lt;a href=&quot;/wiki/Secretary_of_State_(England)&quot; title=&quot;Secretary of State (England)&quot;&gt;principal secretary&lt;/a&gt; and &lt;a href=&quot;/wiki/Spymaster&quot; title=&quot;Spymaster&quot;&gt;spymaster&lt;/a&gt;, was knighted.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1821&quot; title=&quot;1821&quot;&gt;1821&lt;/a&gt; – On the island of &lt;a href=&quot;/wiki/Hispaniola&quot; title=&quot;Hispaniola&quot;&gt;Hispaniola&lt;/a&gt;, General &lt;a href=&quot;/wiki/Jos%C3%A9_N%C3%BA%C3%B1ez_de_C%C3%A1ceres&quot; title=&quot;José Núñez de Cáceres&quot;&gt;José Núñez de Cáceres&lt;/a&gt; established the &lt;b&gt;&lt;a href=&quot;/wiki/Republic_of_Spanish_Haiti&quot; title=&quot;Republic of Spanish Haiti&quot;&gt;Republic of Spanish Haiti&lt;/a&gt;&lt;/b&gt;, which only lasted three months.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Civil_Air_Patrol&quot; title=&quot;Civil Air Patrol&quot;&gt;Civil Air Patrol&lt;/a&gt;&lt;/b&gt;, the civilian auxiliary of the &lt;a href=&quot;/wiki/United_States_Air_Force&quot; title=&quot;United States Air Force&quot;&gt;United States Air Force&lt;/a&gt;, was founded.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt; – A period of political and economic reforms known as the &lt;b&gt;&lt;a href=&quot;/wiki/Croatian_Spring&quot; title=&quot;Croatian Spring&quot;&gt;Croatian Spring&lt;/a&gt;&lt;/b&gt; came to an end as the &lt;a href=&quot;/wiki/League_of_Communists_of_Yugoslavia&quot; title=&quot;League of Communists of Yugoslavia&quot;&gt;League of Communists of Yugoslavia&lt;/a&gt; decided to purge the reformist leadership of Croatia.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1991&quot; title=&quot;1991&quot;&gt;1991&lt;/a&gt; – A &lt;b&gt;&lt;a href=&quot;/wiki/1991_Ukrainian_independence_referendum&quot; title=&quot;1991 Ukrainian independence referendum&quot;&gt;referendum to ratify&lt;/a&gt;&lt;/b&gt; the 24&amp;#160;August &lt;a href=&quot;/wiki/Declaration_of_Independence_of_Ukraine&quot; title=&quot;Declaration of Independence of Ukraine&quot;&gt;Act of Declaration of Independence of Ukraine&lt;/a&gt; passed with more than 92 percent of the votes.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Archie_MacLaren&quot; title=&quot;Archie MacLaren&quot;&gt;Archie MacLaren&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1871)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Anna_Roosevelt_Halsted&quot; title=&quot;Anna Roosevelt Halsted&quot;&gt;Anna Roosevelt Halsted&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1975)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/November_30&quot; title=&quot;November 30&quot;&gt;November 30&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_1&quot; title=&quot;December 1&quot;&gt;December 1&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_2&quot; title=&quot;December 2&quot;&gt;December 2&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211202000000/en</id>
		<title>On this day: December 2</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211202000000/en"/>
		<updated>2021-12-02T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_2&quot; title=&quot;December 2&quot;&gt;December 2&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 199px;&quot;&gt;
&lt;a href=&quot;/wiki/File:La_bataille_d%27Austerlitz._2_decembre_1805_(Fran%C3%A7ois_G%C3%A9rard).jpg&quot; class=&quot;image&quot; title=&quot;The Battle of Austerlitz, 2nd December 1805 by François Gérard&quot;&gt;&lt;img alt=&quot;The Battle of Austerlitz, 2nd December 1805 by François Gérard&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/La_bataille_d%27Austerlitz._2_decembre_1805_%28Fran%C3%A7ois_G%C3%A9rard%29.jpg/199px-La_bataille_d%27Austerlitz._2_decembre_1805_%28Fran%C3%A7ois_G%C3%A9rard%29.jpg&quot; decoding=&quot;async&quot; width=&quot;199&quot; height=&quot;99&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/La_bataille_d%27Austerlitz._2_decembre_1805_%28Fran%C3%A7ois_G%C3%A9rard%29.jpg/299px-La_bataille_d%27Austerlitz._2_decembre_1805_%28Fran%C3%A7ois_G%C3%A9rard%29.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/ba/La_bataille_d%27Austerlitz._2_decembre_1805_%28Fran%C3%A7ois_G%C3%A9rard%29.jpg/398px-La_bataille_d%27Austerlitz._2_decembre_1805_%28Fran%C3%A7ois_G%C3%A9rard%29.jpg 2x&quot; data-file-width=&quot;4000&quot; data-file-height=&quot;1983&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;&lt;i&gt;The Battle of Austerlitz, 2nd December 1805&lt;/i&gt; by &lt;a href=&quot;/wiki/Fran%C3%A7ois_G%C3%A9rard&quot; title=&quot;François Gérard&quot;&gt;François Gérard&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1805&quot; title=&quot;1805&quot;&gt;1805&lt;/a&gt; – &lt;a href=&quot;/wiki/War_of_the_Third_Coalition&quot; title=&quot;War of the Third Coalition&quot;&gt;War of the Third Coalition&lt;/a&gt;: French forces led by &lt;a href=&quot;/wiki/Napoleon&quot; title=&quot;Napoleon&quot;&gt;Napoleon&lt;/a&gt; decisively defeated a Russo-Austrian army commanded by Tsar &lt;a href=&quot;/wiki/Alexander_I_of_Russia&quot; title=&quot;Alexander I of Russia&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;Alexander I&lt;/span&gt;&lt;/a&gt; in the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Austerlitz&quot; title=&quot;Battle of Austerlitz&quot;&gt;Battle of Austerlitz&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(depicted)&lt;/i&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1823&quot; title=&quot;1823&quot;&gt;1823&lt;/a&gt; – U.S. president &lt;a href=&quot;/wiki/James_Monroe&quot; title=&quot;James Monroe&quot;&gt;James Monroe&lt;/a&gt; issued the &lt;b&gt;&lt;a href=&quot;/wiki/Monroe_Doctrine&quot; title=&quot;Monroe Doctrine&quot;&gt;Monroe Doctrine&lt;/a&gt;&lt;/b&gt;, a proclamation of opposition to European colonialism in the &lt;a href=&quot;/wiki/New_World&quot; title=&quot;New World&quot;&gt;New World&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1943&quot; title=&quot;1943&quot;&gt;1943&lt;/a&gt; – &lt;a href=&quot;/wiki/World_War_II&quot; title=&quot;World War II&quot;&gt;World War II&lt;/a&gt;: The &lt;i&gt;&lt;a href=&quot;/wiki/Luftwaffe&quot; title=&quot;Luftwaffe&quot;&gt;Luftwaffe&lt;/a&gt;&lt;/i&gt; conducted &lt;b&gt;&lt;a href=&quot;/wiki/Air_raid_on_Bari&quot; title=&quot;Air raid on Bari&quot;&gt;a surprise air raid&lt;/a&gt;&lt;/b&gt; on &lt;a href=&quot;/wiki/Allies_of_World_War_II&quot; title=&quot;Allies of World War II&quot;&gt;Allied&lt;/a&gt; ships in &lt;a href=&quot;/wiki/Bari&quot; title=&quot;Bari&quot;&gt;Bari&lt;/a&gt;, Italy, sinking twenty-eight ships and releasing one ship's secret cargo of &lt;a href=&quot;/wiki/Mustard_gas&quot; title=&quot;Mustard gas&quot;&gt;mustard gas&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1989&quot; title=&quot;1989&quot;&gt;1989&lt;/a&gt; – The &lt;a href=&quot;/wiki/Malayan_Communist_Party&quot; title=&quot;Malayan Communist Party&quot;&gt;Malayan Communist Party&lt;/a&gt; and the Malaysian government signed &lt;a href=&quot;/wiki/Peace_Agreement_of_Hat_Yai_(1989)&quot; title=&quot;Peace Agreement of Hat Yai (1989)&quot;&gt;a peace accord&lt;/a&gt; to end &lt;b&gt;&lt;a href=&quot;/wiki/Communist_insurgency_in_Malaysia_(1968%E2%80%931989)&quot; title=&quot;Communist insurgency in Malaysia (1968–1989)&quot;&gt;the 21-year Communist insurgency&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2001&quot; title=&quot;2001&quot;&gt;2001&lt;/a&gt; – Less than two months after &lt;b&gt;&lt;a href=&quot;/wiki/Enron_scandal&quot; title=&quot;Enron scandal&quot;&gt;disclosing accounting violations&lt;/a&gt;&lt;/b&gt;, Texas-based energy firm &lt;a href=&quot;/wiki/Enron&quot; title=&quot;Enron&quot;&gt;Enron&lt;/a&gt; filed for &lt;a href=&quot;/wiki/Chapter_11,_Title_11,_United_States_Code&quot; title=&quot;Chapter 11, Title 11, United States Code&quot;&gt;Chapter 11 bankruptcy&lt;/a&gt;, evaporating nearly &lt;span class=&quot;nowrap&quot;&gt;$11 billion&lt;/span&gt; in shareholder wealth.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Vincent_Bourne&quot; title=&quot;Vincent Bourne&quot;&gt;Vincent Bourne&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1747)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Ivan_Bagramyan&quot; title=&quot;Ivan Bagramyan&quot;&gt;Ivan Bagramyan&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1897)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Britney_Spears&quot; title=&quot;Britney Spears&quot;&gt;Britney Spears&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1981)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_1&quot; title=&quot;December 1&quot;&gt;December 1&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_2&quot; title=&quot;December 2&quot;&gt;December 2&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_3&quot; title=&quot;December 3&quot;&gt;December 3&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211203000000/en</id>
		<title>On this day: December 3</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211203000000/en"/>
		<updated>2021-12-03T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_3&quot; title=&quot;December 3&quot;&gt;December 3&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 120px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Emmeline_Freda_du_Faur,_by_George_Edward_Mannering_(1862-1947).jpg&quot; title=&quot;Freda Du Faur&quot;&gt;&lt;img alt=&quot;Freda Du Faur&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Emmeline_Freda_du_Faur%2C_by_George_Edward_Mannering_%281862-1947%29_-_cropped.jpg/120px-Emmeline_Freda_du_Faur%2C_by_George_Edward_Mannering_%281862-1947%29_-_cropped.jpg&quot; decoding=&quot;async&quot; width=&quot;120&quot; height=&quot;160&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Emmeline_Freda_du_Faur%2C_by_George_Edward_Mannering_%281862-1947%29_-_cropped.jpg/180px-Emmeline_Freda_du_Faur%2C_by_George_Edward_Mannering_%281862-1947%29_-_cropped.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Emmeline_Freda_du_Faur%2C_by_George_Edward_Mannering_%281862-1947%29_-_cropped.jpg/240px-Emmeline_Freda_du_Faur%2C_by_George_Edward_Mannering_%281862-1947%29_-_cropped.jpg 2x&quot; data-file-width=&quot;288&quot; data-file-height=&quot;384&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Freda Du Faur&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1800&quot; title=&quot;1800&quot;&gt;1800&lt;/a&gt; – &lt;a href=&quot;/wiki/War_of_the_Second_Coalition&quot; title=&quot;War of the Second Coalition&quot;&gt;War of the Second Coalition&lt;/a&gt;: French forces defeated Austrian and Bavarian troops at the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Hohenlinden&quot; title=&quot;Battle of Hohenlinden&quot;&gt;Battle of Hohenlinden&lt;/a&gt;&lt;/b&gt;, eventually resulting in the Austrians signing the &lt;a href=&quot;/wiki/Treaty_of_Lun%C3%A9ville&quot; title=&quot;Treaty of Lunéville&quot;&gt;Treaty of Lunéville&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1910&quot; title=&quot;1910&quot;&gt;1910&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Freda_Du_Faur&quot; title=&quot;Freda Du Faur&quot;&gt;Freda Du Faur&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; became the first woman to climb &lt;a href=&quot;/wiki/Aoraki_/_Mount_Cook&quot; title=&quot;Aoraki / Mount Cook&quot;&gt;Mount Cook&lt;/a&gt;, the highest peak in New Zealand.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1968&quot; title=&quot;1968&quot;&gt;1968&lt;/a&gt; – &lt;a href=&quot;/wiki/Elvis_Presley&quot; title=&quot;Elvis Presley&quot;&gt;Elvis Presley&lt;/a&gt;'s first television special and first live performance in seven years, &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Elvis_(1968_TV_program)&quot; title=&quot;Elvis (1968 TV program)&quot;&gt;Singer Presents&amp;#160;... Elvis&lt;/a&gt;&lt;/b&gt;&lt;/i&gt;, was broadcast by &lt;a href=&quot;/wiki/NBC&quot; title=&quot;NBC&quot;&gt;NBC&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1976&quot; title=&quot;1976&quot;&gt;1976&lt;/a&gt; – Jamaican &lt;a href=&quot;/wiki/Reggae&quot; title=&quot;Reggae&quot;&gt;reggae&lt;/a&gt; musician &lt;b&gt;&lt;a href=&quot;/wiki/Bob_Marley&quot; title=&quot;Bob Marley&quot;&gt;Bob Marley&lt;/a&gt;&lt;/b&gt; survived &lt;a href=&quot;/wiki/Attempted_assassination_of_Bob_Marley&quot; title=&quot;Attempted assassination of Bob Marley&quot;&gt;an assassination attempt&lt;/a&gt; by seven gunmen.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1994&quot; title=&quot;1994&quot;&gt;1994&lt;/a&gt; – &lt;a href=&quot;/wiki/Sony_Interactive_Entertainment&quot; title=&quot;Sony Interactive Entertainment&quot;&gt;Sony&lt;/a&gt; released the &lt;b&gt;&lt;a href=&quot;/wiki/PlayStation_(console)&quot; title=&quot;PlayStation (console)&quot;&gt;PlayStation&lt;/a&gt;&lt;/b&gt;, the first computer entertainment platform to ship 100&amp;#160;million units.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Birinus&quot; title=&quot;Birinus&quot;&gt;Birinus&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;649&amp;#160;or&amp;#160;650)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Louisa_Susannah_Cheves_McCord&quot; title=&quot;Louisa Susannah Cheves McCord&quot;&gt;Louisa Susannah Cheves McCord&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1810)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Paul_J._Crutzen&quot; title=&quot;Paul J. Crutzen&quot;&gt;Paul J. Crutzen&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1933)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_2&quot; title=&quot;December 2&quot;&gt;December 2&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_3&quot; title=&quot;December 3&quot;&gt;December 3&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_4&quot; title=&quot;December 4&quot;&gt;December 4&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211204000000/en</id>
		<title>On this day: December 4</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211204000000/en"/>
		<updated>2021-12-04T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_4&quot; title=&quot;December 4&quot;&gt;December 4&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Navy_Day_(India)&quot; title=&quot;Navy Day (India)&quot;&gt;Navy Day&lt;/a&gt;&lt;/b&gt; in India
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 132px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Portrait_of_Raja_Ram_Mohun_Roy,_1833.jpg&quot; class=&quot;image&quot; title=&quot;Ram Mohan Roy&quot;&gt;&lt;img alt=&quot;Ram Mohan Roy&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Portrait_of_Raja_Ram_Mohun_Roy%2C_1833.jpg/132px-Portrait_of_Raja_Ram_Mohun_Roy%2C_1833.jpg&quot; decoding=&quot;async&quot; width=&quot;132&quot; height=&quot;148&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Portrait_of_Raja_Ram_Mohun_Roy%2C_1833.jpg/198px-Portrait_of_Raja_Ram_Mohun_Roy%2C_1833.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Portrait_of_Raja_Ram_Mohun_Roy%2C_1833.jpg/264px-Portrait_of_Raja_Ram_Mohun_Roy%2C_1833.jpg 2x&quot; data-file-width=&quot;612&quot; data-file-height=&quot;687&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Ram Mohan Roy&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1370&quot; title=&quot;1370&quot;&gt;1370&lt;/a&gt; – &lt;a href=&quot;/wiki/Hundred_Years%27_War&quot; title=&quot;Hundred Years&amp;#39; War&quot;&gt;Hundred Years' War&lt;/a&gt;: In two separate engagements in the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Pontvallain&quot; title=&quot;Battle of Pontvallain&quot;&gt;Battle of Pontvallain&lt;/a&gt;&lt;/b&gt;, French forces wiped out an English army which had split up because of a dispute between the commanders.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1829&quot; title=&quot;1829&quot;&gt;1829&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Sati_(practice)&quot; title=&quot;Sati (practice)&quot;&gt;Sati&lt;/a&gt;&lt;/b&gt;, the Hindu funeral custom of a widow's &lt;a href=&quot;/wiki/Self-immolation&quot; title=&quot;Self-immolation&quot;&gt;self-immolation&lt;/a&gt; on her husband's &lt;a href=&quot;/wiki/Pyre&quot; title=&quot;Pyre&quot;&gt;pyre&lt;/a&gt;, &lt;a href=&quot;/wiki/Bengal_Sati_Regulation,_1829&quot; title=&quot;Bengal Sati Regulation, 1829&quot;&gt;was prohibited&lt;/a&gt; in parts of &lt;a href=&quot;/wiki/Company_rule_in_India&quot; title=&quot;Company rule in India&quot;&gt;British India&lt;/a&gt; after years of campaigning by &lt;a href=&quot;/wiki/Ram_Mohan_Roy&quot; title=&quot;Ram Mohan Roy&quot;&gt;Ram Mohan Roy&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1909&quot; title=&quot;1909&quot;&gt;1909&lt;/a&gt; – The &lt;a href=&quot;/wiki/Montreal_Canadiens&quot; title=&quot;Montreal Canadiens&quot;&gt;Montreal Canadiens&lt;/a&gt;, the oldest professional &lt;a href=&quot;/wiki/Ice_hockey&quot; title=&quot;Ice hockey&quot;&gt;ice hockey&lt;/a&gt; club in the world, &lt;b&gt;&lt;a href=&quot;/wiki/History_of_the_Montreal_Canadiens&quot; title=&quot;History of the Montreal Canadiens&quot;&gt;were founded&lt;/a&gt;&lt;/b&gt; as a charter member of the &lt;a href=&quot;/wiki/National_Hockey_Association&quot; title=&quot;National Hockey Association&quot;&gt;National Hockey Association&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1949&quot; title=&quot;1949&quot;&gt;1949&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Duncan_Stewart_(colonial_administrator)&quot; title=&quot;Duncan Stewart (colonial administrator)&quot;&gt;Duncan Stewart&lt;/a&gt;&lt;/b&gt;, the British governor of &lt;a href=&quot;/wiki/Crown_Colony_of_Sarawak&quot; title=&quot;Crown Colony of Sarawak&quot;&gt;Sarawak&lt;/a&gt;, was fatally stabbed in &lt;a href=&quot;/wiki/Sibu&quot; title=&quot;Sibu&quot;&gt;Sibu&lt;/a&gt; during his first visit to the colony.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt; – &lt;a href=&quot;/wiki/The_Troubles&quot; title=&quot;The Troubles&quot;&gt;The Troubles&lt;/a&gt;: The &lt;a href=&quot;/wiki/Ulster_Volunteer_Force&quot; title=&quot;Ulster Volunteer Force&quot;&gt;Ulster Volunteer Force&lt;/a&gt;, an &lt;a href=&quot;/wiki/Ulster_loyalism&quot; title=&quot;Ulster loyalism&quot;&gt;Ulster-loyalist&lt;/a&gt; paramilitary group, &lt;b&gt;&lt;a href=&quot;/wiki/McGurk%27s_Bar_bombing&quot; title=&quot;McGurk&amp;#39;s Bar bombing&quot;&gt;detonated a bomb&lt;/a&gt;&lt;/b&gt; at a Catholic-owned pub in &lt;a href=&quot;/wiki/Belfast&quot; title=&quot;Belfast&quot;&gt;Belfast&lt;/a&gt;, Northern Ireland, killing 15 people.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/John_of_Damascus&quot; title=&quot;John of Damascus&quot;&gt;John of Damascus&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;749)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Gregor_MacGregor&quot; title=&quot;Gregor MacGregor&quot;&gt;Gregor MacGregor&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1845)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Roberta_Bondar&quot; title=&quot;Roberta Bondar&quot;&gt;Roberta Bondar&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1945)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_3&quot; title=&quot;December 3&quot;&gt;December 3&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_4&quot; title=&quot;December 4&quot;&gt;December 4&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_5&quot; title=&quot;December 5&quot;&gt;December 5&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211205000000/en</id>
		<title>On this day: December 5</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20211205000000/en"/>
		<updated>2021-12-05T00:00:00Z</updated>

		<summary type="html">&lt;div class=&quot;mw-parser-output&quot;&gt;&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_5&quot; title=&quot;December 5&quot;&gt;December 5&lt;/a&gt;&lt;/b&gt;: &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Krampus&quot; title=&quot;Krampus&quot;&gt;Krampusnacht&lt;/a&gt;&lt;/b&gt;&lt;/i&gt; in parts of Central Europe
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 161px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Siegeofbostonartillery.jpg&quot; class=&quot;image&quot; title=&quot;Henry Knox&amp;#39;s noble train of artillery&quot;&gt;&lt;img alt=&quot;Henry Knox&amp;#39;s noble train of artillery&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/78/Siegeofbostonartillery.jpg/161px-Siegeofbostonartillery.jpg&quot; decoding=&quot;async&quot; width=&quot;161&quot; height=&quot;122&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/7/78/Siegeofbostonartillery.jpg/242px-Siegeofbostonartillery.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/78/Siegeofbostonartillery.jpg/322px-Siegeofbostonartillery.jpg 2x&quot; data-file-width=&quot;1424&quot; data-file-height=&quot;1079&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Henry Knox's noble train of artillery&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/1484&quot; title=&quot;1484&quot;&gt;1484&lt;/a&gt; – &lt;a href=&quot;/wiki/Pope_Innocent_VIII&quot; title=&quot;Pope Innocent VIII&quot;&gt;Pope &lt;span class=&quot;nowrap&quot;&gt;Innocent VIII&lt;/span&gt;&lt;/a&gt; issued the &lt;a href=&quot;/wiki/Papal_bull&quot; title=&quot;Papal bull&quot;&gt;papal bull&lt;/a&gt; &lt;i&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Summis_desiderantes_affectibus&quot; title=&quot;Summis desiderantes affectibus&quot;&gt;Summis desiderantes affectibus&lt;/a&gt;&lt;/b&gt;&lt;/i&gt;, giving &lt;a href=&quot;/wiki/Dominican_Order&quot; title=&quot;Dominican Order&quot;&gt;Dominican&lt;/a&gt; inquisitor &lt;a href=&quot;/wiki/Heinrich_Kramer&quot; title=&quot;Heinrich Kramer&quot;&gt;Heinrich Kramer&lt;/a&gt; explicit authority to prosecute &lt;a href=&quot;/wiki/Witchcraft&quot; title=&quot;Witchcraft&quot;&gt;witchcraft&lt;/a&gt; in Germany.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1775&quot; title=&quot;1775&quot;&gt;1775&lt;/a&gt; – &lt;a href=&quot;/wiki/American_Revolutionary_War&quot; title=&quot;American Revolutionary War&quot;&gt;American Revolutionary War&lt;/a&gt;: &lt;a href=&quot;/wiki/Continental_Army&quot; title=&quot;Continental Army&quot;&gt;Continental Army&lt;/a&gt; colonel &lt;a href=&quot;/wiki/Henry_Knox&quot; title=&quot;Henry Knox&quot;&gt;Henry Knox&lt;/a&gt; arrived at &lt;a href=&quot;/wiki/Fort_Ticonderoga&quot; title=&quot;Fort Ticonderoga&quot;&gt;Fort Ticonderoga&lt;/a&gt; in New York to arrange &lt;b&gt;&lt;a href=&quot;/wiki/Noble_train_of_artillery&quot; title=&quot;Noble train of artillery&quot;&gt;the transport of 60&amp;#160;tons of artillery&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(depicted)&lt;/i&gt; to support the &lt;a href=&quot;/wiki/Siege_of_Boston&quot; title=&quot;Siege of Boston&quot;&gt;Siege of Boston&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1936&quot; title=&quot;1936&quot;&gt;1936&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/1936_Constitution_of_the_Soviet_Union&quot; title=&quot;1936 Constitution of the Soviet Union&quot;&gt;1936 Soviet Constitution&lt;/a&gt;&lt;/b&gt;, also known as the &quot;&lt;a href=&quot;/wiki/Joseph_Stalin&quot; title=&quot;Joseph Stalin&quot;&gt;Stalin&lt;/a&gt; constitution&quot;, was adopted.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/1995&quot; title=&quot;1995&quot;&gt;1995&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Azerbaijan_Airlines_Flight_56&quot; title=&quot;Azerbaijan Airlines Flight 56&quot;&gt;Azerbaijan Airlines Flight&amp;#160;56&lt;/a&gt;&lt;/b&gt; crashed shortly after takeoff from &lt;a href=&quot;/wiki/Nakhchivan_International_Airport&quot; title=&quot;Nakhchivan International Airport&quot;&gt;Nakhchivan Airport&lt;/a&gt;, killing 52 people on board.&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/2005&quot; title=&quot;2005&quot;&gt;2005&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Civil_Partnership_Act_2004&quot; title=&quot;Civil Partnership Act 2004&quot;&gt;Civil Partnership Act&lt;/a&gt;&lt;/b&gt; came into force, granting &lt;a href=&quot;/wiki/Civil_partnership_in_the_United_Kingdom&quot; title=&quot;Civil partnership in the United Kingdom&quot;&gt;civil partnerships in the United Kingdom&lt;/a&gt; rights and responsibilities identical to civil marriage.&lt;/li&gt;&lt;/ul&gt;
&lt;div class=&quot;hlist hlist-separated&quot; style=&quot;margin-top: 0.5em;&quot;&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Jacobus_Anthonie_Meessen&quot; title=&quot;Jacobus Anthonie Meessen&quot;&gt;Jacobus Anthonie Meessen&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1836)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Ren%C3%A9_Crest%C3%A9&quot; title=&quot;René Cresté&quot;&gt;René Cresté&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;born&quot;&gt;b.&lt;/abbr&gt;&amp;#160;1881)&lt;/li&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Amrita_Sher-Gil&quot; title=&quot;Amrita Sher-Gil&quot;&gt;Amrita Sher-Gil&lt;/a&gt;&lt;/b&gt;  (&lt;abbr title=&quot;died&quot;&gt;d.&lt;/abbr&gt;&amp;#160;1941)&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist hlist-separated inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;/wiki/December_4&quot; title=&quot;December 4&quot;&gt;December 4&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_5&quot; title=&quot;December 5&quot;&gt;December 5&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;/wiki/December_6&quot; title=&quot;December 6&quot;&gt;December 6&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist hlist-separated noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;/wiki/List_of_days_of_the_year&quot; title=&quot;List of days of the year&quot;&gt;List of days of the year&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<author><name></name></author>
	</entry>
</feed>