name: linter-check

on: push

jobs:
  linter-check:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip3 install poetry
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: a39c855423d5554a577f727982c5845f2d19a15162b7b5785d1926280d36d8a5
      with:
        coverageCommand: make test-coverage
        debug: true
